
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/10/04
# Impact        : Jobs generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow.operators.oracle_operator import OracleOperator

from airflow import models
from airflow.models import Variable

from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams


# DB_NAME = 'DWH'

my_taskid = "REF_RFQ_STAGE"
REF_RFQ_STAGE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "REF_PIPELINE_STATUS"
REF_PIPELINE_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "REF_PIPELINE_RESULT"
REF_PIPELINE_RESULT = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "REF_PROGRESSION_STATUS"
REF_PROGRESSION_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "REF_BMC"
REF_BMC = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_REVENUE_HIT_RATE"
SDM_REVENUE_HIT_RATE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_EMPLOYEE_H"
SDM_EMPLOYEE_H = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


