
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/10/04
# Impact        : Jobs generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow.operators.oracle_operator import OracleOperator

from airflow import models
from airflow.models import Variable

from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams


# DB_NAME = 'DWH'

my_taskid = "HISTORYCARD"
HISTORYCARD = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "PN_SPC"
PN_SPC = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SUB_SPC"
SUB_SPC = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "RWK_GLOBAL_LOT_WS1"
RWK_GLOBAL_LOT_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "RWK_GLOBAL_LOT_DETAIL_WS1"
RWK_GLOBAL_LOT_DETAIL_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "INSTRUMENT_CORRECT_NQJ"
INSTRUMENT_CORRECT_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "INSTRUMENT_INFO_CORRECT_NQJ"
INSTRUMENT_INFO_CORRECT_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_MTL_CROSS_REFERENCES_V"
MV_MTL_CROSS_REFERENCES_V = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "XX_ERP_ITEM"
XX_ERP_ITEM = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ERPIQC"
ERPIQC = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ERFORM_DOC_MSG_WS1"
ERFORM_DOC_MSG_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "EF_QCEXCEPTION_MST_WS1"
EF_QCEXCEPTION_MST_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "PN_MODULE"
PN_MODULE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "PN_MODULE_MAINTAIN"
PN_MODULE_MAINTAIN = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SPC_ABNORMAL"
SPC_ABNORMAL = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "COPQ_FCTACTUALCOST"
COPQ_FCTACTUALCOST = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MTL_MATERIAL_TRANSACTIONS"
MTL_MATERIAL_TRANSACTIONS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "COPQ_DIMCATEGORY"
COPQ_DIMCATEGORY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "BI_DIMMULTIORG"
BI_DIMMULTIORG = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_ORG_ORGANIZATION_DEF"
MV_ORG_ORGANIZATION_DEF = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ERDRLRR_INSPECTION_HEADER_WS1"
ERDRLRR_INSPECTION_HEADER_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_GL_SETS_OF_BOOKS"
MV_GL_SETS_OF_BOOKS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_WSH_DELIVERABLES_V"
MV_WSH_DELIVERABLES_V = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "QKB_ITEM"
QKB_ITEM = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ERDRLRR_INSPECTION_STATUS_WS1"
ERDRLRR_INSPECTION_STATUS_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ERDRLRR_INSPECTION_DETAIL_WS1"
ERDRLRR_INSPECTION_DETAIL_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ERDRLRR_INSPECTION_RESULT_WS1"
ERDRLRR_INSPECTION_RESULT_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "PLANT"
PLANT = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SAP_MATERIALMASTER"
SAP_MATERIALMASTER = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MATERIALGROUP"
MATERIALGROUP = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "CONTROLTABLE"
CONTROLTABLE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "EMS_LOOKUPVALUE_NQJ"
EMS_LOOKUPVALUE_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "WO_NQJ"
WO_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SPN_TABL_NQJ"
SPN_TABL_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "RESULTTYPE"
RESULTTYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_PDE_EXCEPTION_HEADER_V_WS1"
MV_PDE_EXCEPTION_HEADER_V_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_PDE_EXCEPTION_EQUIP_V_WS1"
MV_PDE_EXCEPTION_EQUIP_V_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_PDE_EXCEPTION_DETAIL_V_WS1"
MV_PDE_EXCEPTION_DETAIL_V_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "PDE_USER_WS1"
PDE_USER_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "QCE_REASON_CODE_WS1"
QCE_REASON_CODE_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "EMS_MANUFACTURER_WS1"
EMS_MANUFACTURER_WS1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MODELTYPE"
MODELTYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "EFLOW_ATLO_SCAR_CN"
EFLOW_ATLO_SCAR_CN = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ATLO_QUESTION_NQJ"
ATLO_QUESTION_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "EF_QCEXCEPTION_MST_NQJ"
EF_QCEXCEPTION_MST_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "ATLO_SCAR_NQJ"
ATLO_SCAR_NQJ = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "MV_XXCS_INCIDENTS_SFCS"
MV_XXCS_INCIDENTS_SFCS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_EMPLOYEE_H"
SDM_EMPLOYEE_H = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MATERIAL_CATEGORY_QA"
SDM_MATERIAL_CATEGORY_QA = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_PRODUCT_TYPE"
SDM_PRODUCT_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MODULE_TYPE"
SDM_MODULE_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_PRODUCT_DEVELOPMENT_TYPE"
SDM_PRODUCT_DEVELOPMENT_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MATERIAL_DEFECT_MODE"
SDM_MATERIAL_DEFECT_MODE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CATEGORY"
SDM_CATEGORY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_QA_RESULT"
SDM_QA_RESULT = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_C_FLOW_DEVELOPMENT_STAGE"
SDM_C_FLOW_DEVELOPMENT_STAGE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_C_FLOW_DEVELOPMENT_DERI"
SDM_C_FLOW_DEVELOPMENT_DERI = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CONTROL_STATION"
SDM_CONTROL_STATION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CONTROL_THE_PROJECT"
SDM_CONTROL_THE_PROJECT = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_TURN_AROUND_TIME"
SDM_TURN_AROUND_TIME = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_RMA_CASE_STATUS"
SDM_RMA_CASE_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_PERSON_IN_CHARGE"
SDM_PERSON_IN_CHARGE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CLOSED_DAY_8D"
SDM_CLOSED_DAY_8D = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_TIER1"
SDM_TIER1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_SHIPPING_DATE"
SDM_SHIPPING_DATE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_RETURN_SOURCE"
SDM_RETURN_SOURCE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_WARRANTY_STATUS"
SDM_WARRANTY_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_INVENTORY_OWNER"
SDM_INVENTORY_OWNER = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MANUFACTURER"
SDM_MANUFACTURER = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CAVITY_NO"
SDM_CAVITY_NO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CASE_CLOSE_STATUS"
SDM_CASE_CLOSE_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_STATION"
SDM_STATION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MO_NO"
SDM_MO_NO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MO_START_MONTH"
SDM_MO_START_MONTH = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MO_PART_TYPE"
SDM_MO_PART_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MP_APPROVE_DATE"
SDM_MP_APPROVE_DATE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_SR_NUMBER"
SDM_SR_NUMBER = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_ATLO_FOR_MP"
SDM_ATLO_FOR_MP = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MP_FLAG"
SDM_MP_FLAG = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_PM"
SDM_PM = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CSD_REASON_PAY"
SDM_CSD_REASON_PAY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CSD_MATERIAL_SCRAP_COS"
SDM_CSD_MATERIAL_SCRAP_COS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CSD_CUSTOMER_PAID_SERV"
SDM_CSD_CUSTOMER_PAID_SERV = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_IQC_DAILY_INPUT_MANP_A"
SDM_IQC_DAILY_INPUT_MANP_A = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_IQC_DAILY_INPUT_MANP"
SDM_IQC_DAILY_INPUT_MANP = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_IQC_DAILY_TOTAL_INSP"
SDM_IQC_DAILY_TOTAL_INSP = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_IQC_AVERAGE_INSPECTION"
SDM_IQC_AVERAGE_INSPECTION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_INCOMING_MATERIAL_REJECT_LOTS"
SDM_INCOMING_MATERIAL_REJECT_LOTS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_SUPPLIER_MATERIAL_PRODUC"
SDM_SUPPLIER_MATERIAL_PRODUC = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CUSTOMER_INSPECTION"
SDM_CUSTOMER_INSPECTION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CUSTOMER_COMPLAIN_CASES"
SDM_CUSTOMER_COMPLAIN_CASES = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_IN_PROCESS_QUALITY_CONTROL"
SDM_IN_PROCESS_QUALITY_CONTROL = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_QUALITY_ALERT_CASES"
SDM_QUALITY_ALERT_CASES = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_EQUIPMENT_ANOMALY_CASE"
SDM_EQUIPMENT_ANOMALY_CASE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_FIXTURE_ANOMALY_CASES"
SDM_FIXTURE_ANOMALY_CASES = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_EQUIPMENT_FIXTURE_ANOM"
SDM_EQUIPMENT_FIXTURE_ANOM = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_FAULT_INJECTION_DR"
SDM_FAULT_INJECTION_DR = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_Q_SCAN_DEFECT_RATE_DR"
SDM_Q_SCAN_DEFECT_RATE_DR = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_FINAL_QUALITY_INSPECTI"
SDM_FINAL_QUALITY_INSPECTI = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_FQC_LRR"
SDM_FQC_LRR = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_QUALITY_HOLD_CASES"
SDM_QUALITY_HOLD_CASES = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CLOSE_WITHIN_SIPULATED"
SDM_CLOSE_WITHIN_SIPULATED = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CUSTOMER_COMPLAIN_FOR"
SDM_CUSTOMER_COMPLAIN_FOR = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_ON_TIME_CLOSE_RATIO_FOR_WN"
SDM_ON_TIME_CLOSE_RATIO_FOR_WN = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CLOSE_WITHIN_14_DAYS_FO"
SDM_CLOSE_WITHIN_14_DAYS_FO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CUSTOMER_COMPLAIN_FOR_S"
SDM_CUSTOMER_COMPLAIN_FOR_S = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CLOSE_WITHIN_14_DAYS_RATIO"
SDM_CLOSE_WITHIN_14_DAYS_RATIO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_FIELD_DEFECT_QUANTITY"
SDM_FIELD_DEFECT_QUANTITY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_ON_SITE_REWORK_QUANTITY"
SDM_ON_SITE_REWORK_QUANTITY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_IN_WARRANTY_RETURN_QUANTITY"
SDM_IN_WARRANTY_RETURN_QUANTITY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_QUALITY_REJECT_QUANTITY"
SDM_QUALITY_REJECT_QUANTITY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_MODELS_WITH_MO_RECORDS"
SDM_MODELS_WITH_MO_RECORDS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CSD_PLANNED_SHIPPING"
SDM_CSD_PLANNED_SHIPPING = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_ACTUAL_CALIBRATION"
SDM_ACTUAL_CALIBRATION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_PLANNED_CALIBRATION"
SDM_PLANNED_CALIBRATION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_CALIBRATION_COMPLETED_RATE"
SDM_CALIBRATION_COMPLETED_RATE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_TICKET_TYPE"
SDM_TICKET_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "SDM_FINAL_QUALITY_INSPECT"
SDM_FINAL_QUALITY_INSPECT = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_MATERIAL_CATEGORY_QA"
DIM_MATERIAL_CATEGORY_QA = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_PRODUCT_TYPE"
DIM_PRODUCT_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_MODULE_TYPE"
DIM_MODULE_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_PRODUCT_DEVELOPMENT_TYPE"
DIM_PRODUCT_DEVELOPMENT_TYPE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_MATERIAL_DEFECT_MODE"
DIM_MATERIAL_DEFECT_MODE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_CATEGORY"
DIM_CATEGORY = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_QA_RESULT"
DIM_QA_RESULT = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_CONTROL_STATION"
DIM_CONTROL_STATION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_CONTROL_THE_PROJECT"
DIM_CONTROL_THE_PROJECT = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_TURN_AROUND_TIME"
DIM_TURN_AROUND_TIME = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_RMA_CASE_STATUS"
DIM_RMA_CASE_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_PERSON_IN_CHARGE"
DIM_PERSON_IN_CHARGE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_CLOSED_DAY_8D"
DIM_CLOSED_DAY_8D = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_TIER1"
DIM_TIER1 = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_SHIPPING_DATE"
DIM_SHIPPING_DATE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_RETURN_SOURCE"
DIM_RETURN_SOURCE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_WARRANTY_STATUS"
DIM_WARRANTY_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_INVENTORY_OWNER"
DIM_INVENTORY_OWNER = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_CAVITY_NO"
DIM_CAVITY_NO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_CASE_CLOSE_STATUS"
DIM_CASE_CLOSE_STATUS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_STATION"
DIM_STATION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_C_FLOW_DEVELOPMENT_STAGE"
DIM_C_FLOW_DEVELOPMENT_STAGE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_C_FLOW_DEVELOPMENT_DERI"
DIM_C_FLOW_DEVELOPMENT_DERI = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_ATLO_FOR_MP"
DIM_ATLO_FOR_MP = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_MP_FLAG"
DIM_MP_FLAG = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_PM"
DIM_PM = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_MO_NO"
DIM_MO_NO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_MO_START_MONTH"
DIM_MO_START_MONTH = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_MP_APPROVE_DATE"
DIM_MP_APPROVE_DATE = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "DIM_SR_NUMBER"
DIM_SR_NUMBER = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CSD_MATERIAL_SCRAP_COS"
FCT_CSD_MATERIAL_SCRAP_COS = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CSD_CUSTOMER_PAID_SERV"
FCT_CSD_CUSTOMER_PAID_SERV = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_IQC_DAILY_INPUT_MANP"
FCT_IQC_DAILY_INPUT_MANP = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_IQC_DAILY_TOTAL_INSP"
FCT_IQC_DAILY_TOTAL_INSP = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_IQC_AVERAGE_INSPECTION"
FCT_IQC_AVERAGE_INSPECTION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_SUPPLIER_MATERIAL_PRODUC"
FCT_SUPPLIER_MATERIAL_PRODUC = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CUSTOMER_INSPECTION"
FCT_CUSTOMER_INSPECTION = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CUSTOMER_COMPLAIN_CASES"
FCT_CUSTOMER_COMPLAIN_CASES = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_FAULT_INJECTION_DR"
FCT_FAULT_INJECTION_DR = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_Q_SCAN_DEFECT_RATE_DR"
FCT_Q_SCAN_DEFECT_RATE_DR = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_QUALITY_HOLD_CASES"
FCT_QUALITY_HOLD_CASES = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CLOSE_WITHIN_SIPULATED"
FCT_CLOSE_WITHIN_SIPULATED = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CUSTOMER_COMPLAIN_FOR"
FCT_CUSTOMER_COMPLAIN_FOR = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_ON_TIME_CLOSE_RATIO_FOR_WN"
FCT_ON_TIME_CLOSE_RATIO_FOR_WN = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CLOSE_WITHIN_14_DAYS_FO"
FCT_CLOSE_WITHIN_14_DAYS_FO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CUSTOMER_COMPLAIN_FOR_S"
FCT_CUSTOMER_COMPLAIN_FOR_S = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


my_taskid = "FCT_CLOSE_WITHIN_14_DAYS_RATIO"
FCT_CLOSE_WITHIN_14_DAYS_RATIO = OracleOperator(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(1),
    pool='postgres_dwh')


