



# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/11/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
# import sqlg_jobs 
import sqlg_jobs_SCM


#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams

def f_SYS_STS_STG():
    logging.info('Control flow: STAGE status ')

args = {
    'owner': 'airflow',
    'start_date': airflow.utils.dates.days_ago(1),
    'provide_context': True
}

tmpl_search_path = Variable.get("sql_path")

my_taskid = 'SYS_STS_STG'
D_STG_INIT = airflow.DAG(
    'D_STG_INIT',
    schedule_interval=timedelta(1),
    default_args=args,
    template_searchpath=tmpl_search_path,    
    max_active_runs=1)

SYS_STS_STG = PythonOperator(task_id=my_taskid,
                    python_callable=f_SYS_STS_STG,
                    provide_context=False,
                    dag=D_STG_INIT)

my_taskid = 'D_STG_INITxSYS_STS_STG'                    
D_STG_INITxSYS_STS_STG = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_STG_INIT',
    external_task_id='SYS_STS_STG',
    execution_delta=None,  # Same day as today
    )

# Flow dag    
# DB_NAME = 'DWH'    
D_ODS_SCM = airflow.DAG(    "D_ODS_SCM",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_SCM"
D_STG_INITxSYS_STS_STGxD_SDM_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs_SCM.BRAND_CATEGORY.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BRAND_CATEGORY)

sqlg_jobs_SCM.BRAND_DETAIL_SCORE_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BRAND_DETAIL_SCORE_V)

sqlg_jobs_SCM.PLM_BRAND_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PLM_BRAND_V)

sqlg_jobs_SCM.VPE_RANKING_VALUE.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.VPE_RANKING_VALUE)

sqlg_jobs_SCM.MTL_CATEGORY_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_CATEGORY_B)

sqlg_jobs_SCM.MTL_CROSS_REFERENCES_VL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_CROSS_REFERENCES_VL)

sqlg_jobs_SCM.MV_ORG_ORG_DEF.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MV_ORG_ORG_DEF)

sqlg_jobs_SCM.PO_HEADERS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_HEADERS_ALL)

sqlg_jobs_SCM.PO_LINES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_LINES_ALL)

sqlg_jobs_SCM.AP_SUPPLIERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.AP_SUPPLIERS)

sqlg_jobs_SCM.AP_SUPPLIER_SITES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.AP_SUPPLIER_SITES_ALL)

sqlg_jobs_SCM.CST_COST_TYPES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.CST_COST_TYPES)

sqlg_jobs_SCM.CST_ITEM_COSTS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.CST_ITEM_COSTS)

sqlg_jobs_SCM.MTL_SECONDARY_INVENTORIES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_SECONDARY_INVENTORIES)

sqlg_jobs_SCM.RCV_TRANSACTIONS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.RCV_TRANSACTIONS)

sqlg_jobs_SCM.BOM_COMPONENTS_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BOM_COMPONENTS_B)

sqlg_jobs_SCM.BOM_STRUCTURES_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BOM_STRUCTURES_B)

sqlg_jobs_SCM.MTL_ONHAND_QUANTITIES_DETAIL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_ONHAND_QUANTITIES_DETAIL)

sqlg_jobs_SCM.MTL_PARAMETERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_PARAMETERS)

sqlg_jobs_SCM.MTL_TRANSACTION_REASONS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_TRANSACTION_REASONS)

sqlg_jobs_SCM.MTL_TRANSACTION_TYPES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_TRANSACTION_TYPES)

sqlg_jobs_SCM.MV_MTL_CATEGORIES_B_KFV.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MV_MTL_CATEGORIES_B_KFV)

sqlg_jobs_SCM.MV_MTL_ITEM_LOCATIONS_KFV.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MV_MTL_ITEM_LOCATIONS_KFV)

sqlg_jobs_SCM.UI_INV_ADS_SUMMARY_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.UI_INV_ADS_SUMMARY_V)

sqlg_jobs_SCM.ERFQ_ITEMVENDOR.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.ERFQ_ITEMVENDOR)

sqlg_jobs_SCM.ERFQ_PRICEDATA_OBC.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.ERFQ_PRICEDATA_OBC)

sqlg_jobs_SCM.SCM_RISK_SHIPMENT_UPLOAD.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.SCM_RISK_SHIPMENT_UPLOAD)

sqlg_jobs_SCM.XXPO_HUB_INVENTORY_TEMP.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.XXPO_HUB_INVENTORY_TEMP)

sqlg_jobs_SCM.VPE_BRAND_SCORE_FINAL_ADJ.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.VPE_BRAND_SCORE_FINAL_ADJ)

sqlg_jobs_SCM.NSP_PO_LINES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.NSP_PO_LINES)

sqlg_jobs_SCM.NSP_PO_HEADERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.NSP_PO_HEADERS)

sqlg_jobs_SCM.RVL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.RVL)

sqlg_jobs_SCM.PO_LINE_LOCATIONS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_LINE_LOCATIONS_ALL)

sqlg_jobs_SCM.PO_REQUISITION_LINES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_REQUISITION_LINES_ALL)

sqlg_jobs_SCM.PO_REQ_DISTRIBUTIONS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_REQ_DISTRIBUTIONS_ALL)

sqlg_jobs_SCM.XXPO_STR_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.XXPO_STR_ALL)

D_SDM_SCM = airflow.DAG(    "D_SDM_SCM",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_SCM"
D_STG_INITxSYS_STS_STGxD_SDM_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs_SCM.SDM_BLANKET_PURCHASE_AGREEMENT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_BLANKET_PURCHASE_AGREEMENT)

sqlg_jobs_SCM.SDM_HUB_IVNT_AMT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_HUB_IVNT_AMT)

sqlg_jobs_SCM.SDM_AGE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_AGE)

sqlg_jobs_SCM.SDM_WNEWEB_MONTHLY_END_STOCK_AMT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_WNEWEB_MONTHLY_END_STOCK_AMT)

sqlg_jobs_SCM.SDM_CONTRACT_PRICE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CONTRACT_PRICE)

sqlg_jobs_SCM.SDM_BOM.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_BOM)

sqlg_jobs_SCM.SDM_CALIX_CTB_SUPPLY_AND_DEMAND_REPORT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CALIX_CTB_SUPPLY_AND_DEMAND_REPORT)

sqlg_jobs_SCM.SDM_CTB_GENERAL_DEMAND.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CTB_GENERAL_DEMAND)

sqlg_jobs_SCM.SDM_CTB_GENERAL_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CTB_GENERAL_SUPPLY)

sqlg_jobs_SCM.SDM_CAPACITY_BALANCE_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CAPACITY_BALANCE_ADS)

sqlg_jobs_SCM.SDM_CAPACITY_BALANCE_AMT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CAPACITY_BALANCE_AMT)

sqlg_jobs_SCM.SDM_CAV_QTY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CAV_QTY)

sqlg_jobs_SCM.SDM_CRITICAL_PART_SHORTAGE_QTY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CRITICAL_PART_SHORTAGE_QTY)

sqlg_jobs_SCM.SDM_CAVS_BY_VPE_RANKING_C_AND_D_RATE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CAVS_BY_VPE_RANKING_C_AND_D_RATE)

sqlg_jobs_SCM.SDM_EE_ITEM_FAB_ASSEMBLY_TEST_SHIPMENT_LO.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_EE_ITEM_FAB_ASSEMBLY_TEST_SHIPMENT_LO)

sqlg_jobs_SCM.SDM_ENDING_COST_RM.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_ENDING_COST_RM)

sqlg_jobs_SCM.SDM_DELIVERED_DUTY_PAID_IVNT_AMT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_DELIVERED_DUTY_PAID_IVNT_AMT)

sqlg_jobs_SCM.SDM_APL_CGY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_APL_CGY)

sqlg_jobs_SCM.SDM_CST_LIABILITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_CST_LIABILITY)

sqlg_jobs_SCM.SDM_BATCH_STOCK_IN.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_BATCH_STOCK_IN)

sqlg_jobs_SCM.SDM_BUY_AND_SELL_PARTS_AMT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_BUY_AND_SELL_PARTS_AMT)

sqlg_jobs_SCM.SDM_SHIPMENT_AMT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_SHIPMENT_AMT)

sqlg_jobs_SCM.SDM_RFQ_FOR_NEW_PROJECT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs_SCM.SDM_RFQ_FOR_NEW_PROJECT)

