
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/11/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
# import sqlg_jobs 
import sqlg_jobs_
			

#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams

def f_SYS_STS_STG():
    logging.info('Control flow: STAGE status ')

args = {
    'owner': 'airflow',
    'start_date': airflow.utils.dates.days_ago(1),
    'provide_context': True
}

tmpl_search_path = Variable.get("sql_path")

my_taskid = 'SYS_STS_STG'
D_STG_INIT = airflow.DAG(
    'D_STG_INIT',
    schedule_interval=timedelta(1),
    default_args=args,
    template_searchpath=tmpl_search_path,    
    max_active_runs=1)

SYS_STS_STG = PythonOperator(task_id=my_taskid,
                    python_callable=f_SYS_STS_STG,
                    provide_context=False,
                    dag=D_STG_INIT)

my_taskid = 'D_STG_INITxSYS_STS_STG'                    
D_STG_INITxSYS_STS_STG = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_STG_INIT',
    external_task_id='SYS_STS_STG',
    execution_delta=None,  # Same day as today
    )

# Flow dag    
# DB_NAME = 'DWH'    
D_ODS_SCM = airflow.DAG(    "D_ODS_SCM",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_ODS_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_QAM"
D_STG_INITxSYS_STS_STGxD_ODS_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_SCM"
D_STG_INITxSYS_STS_STGxD_SDM_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_QAM"
D_STG_INITxSYS_STS_STGxD_SDM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_QAM"
D_STG_INITxSYS_STS_STGxD_DM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs.BRAND_CATEGORY.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.BRAND_CATEGORY)

sqlg_jobs.BRAND_DETAIL_SCORE_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.BRAND_DETAIL_SCORE_V)

sqlg_jobs.PLM_BRAND_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.PLM_BRAND_V)

sqlg_jobs.VPE_RANKING_VALUE.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.VPE_RANKING_VALUE)

sqlg_jobs.MTL_CATEGORY_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MTL_CATEGORY_B)

sqlg_jobs.MTL_CROSS_REFERENCES_VL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MTL_CROSS_REFERENCES_VL)

sqlg_jobs.MV_ORG_ORG_DEF.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MV_ORG_ORG_DEF)

sqlg_jobs.PO_HEADERS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.PO_HEADERS_ALL)

sqlg_jobs.PO_LINES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.PO_LINES_ALL)

sqlg_jobs.AP_SUPPLIERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.AP_SUPPLIERS)

sqlg_jobs.AP_SUPPLIER_SITES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.AP_SUPPLIER_SITES_ALL)

sqlg_jobs.CST_COST_TYPES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.CST_COST_TYPES)

sqlg_jobs.CST_ITEM_COSTS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.CST_ITEM_COSTS)

sqlg_jobs.MTL_SECONDARY_INVENTORIES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MTL_SECONDARY_INVENTORIES)

sqlg_jobs.RCV_TRANSACTIONS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.RCV_TRANSACTIONS)

sqlg_jobs.BOM_COMPONENTS_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.BOM_COMPONENTS_B)

sqlg_jobs.BOM_STRUCTURES_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.BOM_STRUCTURES_B)

sqlg_jobs.MTL_ONHAND_QUANTITIES_DETAIL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MTL_ONHAND_QUANTITIES_DETAIL)

sqlg_jobs.MTL_PARAMETERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MTL_PARAMETERS)

sqlg_jobs.MTL_TRANSACTION_REASONS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MTL_TRANSACTION_REASONS)

sqlg_jobs.MTL_TRANSACTION_TYPES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MTL_TRANSACTION_TYPES)

sqlg_jobs.MV_MTL_CATEGORIES_B_KFV.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MV_MTL_CATEGORIES_B_KFV)

sqlg_jobs.MV_MTL_ITEM_LOCATIONS_KFV.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.MV_MTL_ITEM_LOCATIONS_KFV)

sqlg_jobs.UI_INV_ADS_SUMMARY_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.UI_INV_ADS_SUMMARY_V)

sqlg_jobs.ERFQ_ITEMVENDOR.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.ERFQ_ITEMVENDOR)

sqlg_jobs.ERFQ_PRICEDATA_OBC.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.ERFQ_PRICEDATA_OBC)

sqlg_jobs.SCM_RISK_SHIPMENT_UPLOAD.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.SCM_RISK_SHIPMENT_UPLOAD)

sqlg_jobs.XXPO_HUB_INVENTORY_TEMP.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.XXPO_HUB_INVENTORY_TEMP)

sqlg_jobs.VPE_BRAND_SCORE_FINAL_ADJ.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.VPE_BRAND_SCORE_FINAL_ADJ)

sqlg_jobs.NSP_PO_LINES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.NSP_PO_LINES)

sqlg_jobs.NSP_PO_HEADERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.NSP_PO_HEADERS)

sqlg_jobs.RVL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.RVL)

sqlg_jobs.PO_LINE_LOCATIONS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.PO_LINE_LOCATIONS_ALL)

sqlg_jobs.PO_REQUISITION_LINES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.PO_REQUISITION_LINES_ALL)

sqlg_jobs.PO_REQ_DISTRIBUTIONS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.PO_REQ_DISTRIBUTIONS_ALL)

sqlg_jobs.XXPO_STR_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs.XXPO_STR_ALL)

D_ODS_QAM = airflow.DAG(    "D_ODS_QAM",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_ODS_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_QAM"
D_STG_INITxSYS_STS_STGxD_ODS_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_SCM"
D_STG_INITxSYS_STS_STGxD_SDM_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_QAM"
D_STG_INITxSYS_STS_STGxD_SDM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_QAM"
D_STG_INITxSYS_STS_STGxD_DM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs.HISTORYCARD.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.HISTORYCARD)

sqlg_jobs.PN_SPC.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.PN_SPC)

sqlg_jobs.SUB_SPC.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.SUB_SPC)

sqlg_jobs.RWK_GLOBAL_LOT_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.RWK_GLOBAL_LOT_WS1)

sqlg_jobs.RWK_GLOBAL_LOT_DETAIL_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.RWK_GLOBAL_LOT_DETAIL_WS1)

sqlg_jobs.INSTRUMENT_CORRECT_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.INSTRUMENT_CORRECT_NQJ)

sqlg_jobs.INSTRUMENT_INFO_CORRECT_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.INSTRUMENT_INFO_CORRECT_NQJ)

sqlg_jobs.MV_MTL_CROSS_REFERENCES_V.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_MTL_CROSS_REFERENCES_V)

sqlg_jobs.XX_ERP_ITEM.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.XX_ERP_ITEM)

sqlg_jobs.ERPIQC.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ERPIQC)

sqlg_jobs.ERFORM_DOC_MSG_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ERFORM_DOC_MSG_WS1)

sqlg_jobs.EF_QCEXCEPTION_MST_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.EF_QCEXCEPTION_MST_WS1)

sqlg_jobs.PN_MODULE.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.PN_MODULE)

sqlg_jobs.PN_MODULE_MAINTAIN.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.PN_MODULE_MAINTAIN)

sqlg_jobs.SPC_ABNORMAL.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.SPC_ABNORMAL)

sqlg_jobs.COPQ_FCTACTUALCOST.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.COPQ_FCTACTUALCOST)

sqlg_jobs.MTL_MATERIAL_TRANSACTIONS.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MTL_MATERIAL_TRANSACTIONS)

sqlg_jobs.COPQ_DIMCATEGORY.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.COPQ_DIMCATEGORY)

sqlg_jobs.BI_DIMMULTIORG.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.BI_DIMMULTIORG)

sqlg_jobs.MV_ORG_ORGANIZATION_DEF.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_ORG_ORGANIZATION_DEF)

sqlg_jobs.ERDRLRR_INSPECTION_HEADER_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ERDRLRR_INSPECTION_HEADER_WS1)

sqlg_jobs.MV_GL_SETS_OF_BOOKS.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_GL_SETS_OF_BOOKS)

sqlg_jobs.MV_WSH_DELIVERABLES_V.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_WSH_DELIVERABLES_V)

sqlg_jobs.QKB_ITEM.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.QKB_ITEM)

sqlg_jobs.ERDRLRR_INSPECTION_STATUS_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ERDRLRR_INSPECTION_STATUS_WS1)

sqlg_jobs.ERDRLRR_INSPECTION_DETAIL_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ERDRLRR_INSPECTION_DETAIL_WS1)

sqlg_jobs.ERDRLRR_INSPECTION_RESULT_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ERDRLRR_INSPECTION_RESULT_WS1)

sqlg_jobs.PLANT.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.PLANT)

sqlg_jobs.SAP_MATERIALMASTER.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.SAP_MATERIALMASTER)

sqlg_jobs.MATERIALGROUP.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MATERIALGROUP)

sqlg_jobs.CONTROLTABLE.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.CONTROLTABLE)

sqlg_jobs.EMS_LOOKUPVALUE_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.EMS_LOOKUPVALUE_NQJ)

sqlg_jobs.WO_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.WO_NQJ)

sqlg_jobs.SPN_TABL_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.SPN_TABL_NQJ)

sqlg_jobs.RESULTTYPE.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.RESULTTYPE)

sqlg_jobs.MV_PDE_EXCEPTION_HEADER_V_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_PDE_EXCEPTION_HEADER_V_WS1)

sqlg_jobs.MV_PDE_EXCEPTION_EQUIP_V_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_PDE_EXCEPTION_EQUIP_V_WS1)

sqlg_jobs.MV_PDE_EXCEPTION_DETAIL_V_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_PDE_EXCEPTION_DETAIL_V_WS1)

sqlg_jobs.PDE_USER_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.PDE_USER_WS1)

sqlg_jobs.QCE_REASON_CODE_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.QCE_REASON_CODE_WS1)

sqlg_jobs.EMS_MANUFACTURER_WS1.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.EMS_MANUFACTURER_WS1)

sqlg_jobs.MODELTYPE.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MODELTYPE)

sqlg_jobs.EFLOW_ATLO_SCAR_CN.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.EFLOW_ATLO_SCAR_CN)

sqlg_jobs.ATLO_QUESTION_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ATLO_QUESTION_NQJ)

sqlg_jobs.EF_QCEXCEPTION_MST_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.EF_QCEXCEPTION_MST_NQJ)

sqlg_jobs.ATLO_SCAR_NQJ.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.ATLO_SCAR_NQJ)

sqlg_jobs.MV_XXCS_INCIDENTS_SFCS.dag=D_ODS_QAM
D_STG_INITxSYS_STS_STGxD_ODS_QAM.set_downstream(sqlg_jobs.MV_XXCS_INCIDENTS_SFCS)

D_SDM_SCM = airflow.DAG(    "D_SDM_SCM",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_ODS_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_QAM"
D_STG_INITxSYS_STS_STGxD_ODS_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_SCM"
D_STG_INITxSYS_STS_STGxD_SDM_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_QAM"
D_STG_INITxSYS_STS_STGxD_SDM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_QAM"
D_STG_INITxSYS_STS_STGxD_DM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs.SDM_NVS_VENDOR_CATEGORY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_NVS_VENDOR_CATEGORY)

sqlg_jobs.SDM_NVS_STATUS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_NVS_STATUS)

sqlg_jobs.SDM_SUPPLIER_CODE_APPLICATION_STATUS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SUPPLIER_CODE_APPLICATION_STATUS)

sqlg_jobs.SDM_APPLICATION_CATEGORY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_APPLICATION_CATEGORY)

sqlg_jobs.SDM_CAV_PROPORTION_OF_NVS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CAV_PROPORTION_OF_NVS)

sqlg_jobs.SDM_NVS_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_NVS_QUANTITY)

sqlg_jobs.SDM_CAV_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CAV_QUANTITY)

sqlg_jobs.SDM_SUPPLIER_TYPE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SUPPLIER_TYPE)

sqlg_jobs.SDM_SUPPLIER_CATEGORY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SUPPLIER_CATEGORY)

sqlg_jobs.SDM_SUPPLIER_SUBCATEGORY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SUPPLIER_SUBCATEGORY)

sqlg_jobs.SDM_RVL.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RVL)

sqlg_jobs.SDM_CAVPROPORTION_OF_RT_SUPPLIER_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CAVPROPORTION_OF_RT_SUPPLIER_QUANTITY)

sqlg_jobs.SDM_RT_SUPPLIER_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RT_SUPPLIER_QUANTITY)

sqlg_jobs.SDM_VPE_RANKING.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_VPE_RANKING)

sqlg_jobs.SDM_CAV_BY_VPE_RANKING_C_AND_D_RATE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CAV_BY_VPE_RANKING_C_AND_D_RATE)

sqlg_jobs.SDM_BRAND_NAME.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_BRAND_NAME)

sqlg_jobs.SDM_OPERATION_UNIT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_OPERATION_UNIT)

sqlg_jobs.SDM_RVL_HIT_RATE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RVL_HIT_RATE)

sqlg_jobs.SDM_NEW_BOM_ITEM_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_NEW_BOM_ITEM_QUANTITY)

sqlg_jobs.SDM_RVL_ITEM_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RVL_ITEM_QUANTITY)

sqlg_jobs.SDM_BPA.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_BPA)

sqlg_jobs.SDM_RT_QTY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RT_QTY)

sqlg_jobs.SDM_MATERIAL_DEMAND_INFORMATION.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_MATERIAL_DEMAND_INFORMATION)

sqlg_jobs.SDM_PO_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_PO_AMOUNT)

sqlg_jobs.SDM_RT_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RT_AMOUNT)

sqlg_jobs.SDM_RFQ_FOR_NEW_PROJECT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RFQ_FOR_NEW_PROJECT)

sqlg_jobs.SDM_SHIPMENT_LOCATION.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SHIPMENT_LOCATION)

sqlg_jobs.SDM_MFG_LOCATION.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_MFG_LOCATION)

sqlg_jobs.SDM_VENDOR_NAME.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_VENDOR_NAME)

sqlg_jobs.SDM_RISK_ASSESSMENT_SUPPLIER_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RISK_ASSESSMENT_SUPPLIER_QUANTITY)

sqlg_jobs.SDM_RISK_ASSESSMENT_ITEM_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RISK_ASSESSMENT_ITEM_QUANTITY)

sqlg_jobs.SDM_SOURCER.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SOURCER)

sqlg_jobs.SDM_MRO_COST_DOWN_RATE_MANAGEMENT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_MRO_COST_DOWN_RATE_MANAGEMENT)

sqlg_jobs.SDM_PR_PRICE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_PR_PRICE)

sqlg_jobs.SDM_FORMER_PURCHASE_PRICE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_FORMER_PURCHASE_PRICE)

sqlg_jobs.SDM_CONTRACT_PRICE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CONTRACT_PRICE)

sqlg_jobs.SDM_PO_PRICE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_PO_PRICE)

sqlg_jobs.SDM_FORECAST_CHANGE_ANALYSIS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_FORECAST_CHANGE_ANALYSIS)

sqlg_jobs.SDM_FORECAST_CHANGE_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_FORECAST_CHANGE_QUANTITY)

sqlg_jobs.SDM_FORECAST_CHANGE-ITEM_COST.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_FORECAST_CHANGE-ITEM_COST)

sqlg_jobs.SDM_BOM.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_BOM)

sqlg_jobs.SDM_CTB_REPORT-CALIX.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CTB_REPORT-CALIX)

sqlg_jobs.SDM_CTB_GENERAL_DEMAND.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CTB_GENERAL_DEMAND)

sqlg_jobs.SDM_CTB_GENERAL_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CTB_GENERAL_SUPPLY)

sqlg_jobs.SDM_RISK_SHIPMENT_REASON_CODE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RISK_SHIPMENT_REASON_CODE)

sqlg_jobs.SDM_RISK_SHIPMENT_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RISK_SHIPMENT_AMOUNT)

sqlg_jobs.SDM_MODEL_RISK_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_MODEL_RISK_QUANTITY)

sqlg_jobs.SDM_ITEM_COST.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_ITEM_COST)

sqlg_jobs.SDM_CRITICAL_PART_SHORTAGE_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CRITICAL_PART_SHORTAGE_QUANTITY)

sqlg_jobs.SDM_GLOBAL_AVERAGE_DAYS_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_GLOBAL_AVERAGE_DAYS_SUPPLY)

sqlg_jobs.SDM_RAW_MATERIAL_INVENTORY_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RAW_MATERIAL_INVENTORY_AMOUNT)

sqlg_jobs.SDM_RAW_MATERIAL_INVENTORY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_RAW_MATERIAL_INVENTORY)

sqlg_jobs.SDM_FORCAST_CHANGE_IMPACT_OF_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_FORCAST_CHANGE_IMPACT_OF_ADS)

sqlg_jobs.SDM_FORCAST_CANCEL_OR_POSTPONE_QUANTITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_FORCAST_CANCEL_OR_POSTPONE_QUANTITY)

sqlg_jobs.SDM_NON-CURR_M_FCST_CHANGE_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_NON-CURR_M_FCST_CHANGE_ADS)

sqlg_jobs.SDM_NON-CURR_M_FCST_CHANGE_AMOUNT_OF_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_NON-CURR_M_FCST_CHANGE_AMOUNT_OF_ADS)

sqlg_jobs.SDM_LOCATOR.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_LOCATOR)

sqlg_jobs.SDM_AGE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_AGE)

sqlg_jobs.SDM_HUB_INVENTORY_AVERAGE_DAYS_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_HUB_INVENTORY_AVERAGE_DAYS_SUPPLY)

sqlg_jobs.SDM_HUB_INVENTORY_STORAGE_AGE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_HUB_INVENTORY_STORAGE_AGE)

sqlg_jobs.SDM_HUB_INVENTORY_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_HUB_INVENTORY_AMOUNT)

sqlg_jobs.SDM_BATCH_STOCK_IN.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_BATCH_STOCK_IN)

sqlg_jobs.SDM_INVENTORY_AT_CACULATE_TIME.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_INVENTORY_AT_CACULATE_TIME)

sqlg_jobs.SDM_STOCK_IN_DAYS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_STOCK_IN_DAYS)

sqlg_jobs.SDM_WNEWEB_STOCK_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_WNEWEB_STOCK_ADS)

sqlg_jobs.SDM_WNEWEB_STOCK_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_WNEWEB_STOCK_AMOUNT)

sqlg_jobs.SDM_WNEWEB_MONTHLY_END_STOCK_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_WNEWEB_MONTHLY_END_STOCK_AMOUNT)

sqlg_jobs.SDM_IN_TRANSIT_INVENTORY_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_IN_TRANSIT_INVENTORY_AMOUNT)

sqlg_jobs.SDM_SHIPMENT_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SHIPMENT_AMOUNT)

sqlg_jobs.SDM_ORGANIZATION.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_ORGANIZATION)

sqlg_jobs.SDM_DDP_INVENTORY_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_DDP_INVENTORY_ADS)

sqlg_jobs.SDM_DDP_INVENTORY_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_DDP_INVENTORY_AMOUNT)

sqlg_jobs.SDM_DEFERRED_COST_OF_GOODS_SOLD_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_DEFERRED_COST_OF_GOODS_SOLD_ADS)

sqlg_jobs.SDM_INTRANSIT_AVERAGE_DAYS_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_INTRANSIT_AVERAGE_DAYS_SUPPLY)

sqlg_jobs.SDM_INTRANSIT_STOCK_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_INTRANSIT_STOCK_AMOUNT)

sqlg_jobs.SDM_LOGISTIC_IMPORT_INTRANSIT_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_LOGISTIC_IMPORT_INTRANSIT_ADS)

sqlg_jobs.SDM_LOGISTIC_IMPORT_INTRANSIT_STOCK_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_LOGISTIC_IMPORT_INTRANSIT_STOCK_AMOUNT)

sqlg_jobs.SDM_CAPACITY_BALANCE_AVERAGE_DAYS_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CAPACITY_BALANCE_AVERAGE_DAYS_SUPPLY)

sqlg_jobs.SDM_CAPACITY_BALANCE_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CAPACITY_BALANCE_AMOUNT)

sqlg_jobs.SDM_DOWNSIZNG_ITEMS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_DOWNSIZNG_ITEMS)

sqlg_jobs.SDM_CUSTOMER_DEMAND_DOWNSIDE_STOCK_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CUSTOMER_DEMAND_DOWNSIDE_STOCK_ADS)

sqlg_jobs.SDM_CUSTOMER_DEMAND_DOWNSIDE_STOCK_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CUSTOMER_DEMAND_DOWNSIDE_STOCK_AMOUNT)

sqlg_jobs.SDM_CUSTOMER_DEMAND_DOWNSIDE_STOCK_AGE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CUSTOMER_DEMAND_DOWNSIDE_STOCK_AGE)

sqlg_jobs.SDM_CUSTOMER_LIABILITY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_CUSTOMER_LIABILITY)

sqlg_jobs.SDM_LIABILITY_STOCK_AVERAGE_DAYS_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_LIABILITY_STOCK_AVERAGE_DAYS_SUPPLY)

sqlg_jobs.SDM_LIABILITY_STOCK_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_LIABILITY_STOCK_AMOUNT)

sqlg_jobs.SDM_LIABILITY_STOCK_AGE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_LIABILITY_STOCK_AGE)

sqlg_jobs.SDM_STRATEGIC_PREPARATI_ON_STOCK_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_STRATEGIC_PREPARATI_ON_STOCK_ADS)

sqlg_jobs.SDM_STRATEGIC_PREPARATI_ON_STOCK_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_STRATEGIC_PREPARATI_ON_STOCK_AMOUNT)

sqlg_jobs.SDM_SCRAP_REASON_CODE.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SCRAP_REASON_CODE)

sqlg_jobs.SDM_SCRAP_AVERAGE_DAYS_SUPPLY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SCRAP_AVERAGE_DAYS_SUPPLY)

sqlg_jobs.SDM_SCRAP_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SCRAP_AMOUNT)

sqlg_jobs.SDM_BUY_AND_SELL_PARTS_AMOUNT.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_BUY_AND_SELL_PARTS_AMOUNT)

sqlg_jobs.SDM_MANUFACTURING_INVENTORY_ADS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_MANUFACTURING_INVENTORY_ADS)

sqlg_jobs.SDM_SITE_NORMAL_ORGANIZATION_RM_INVENTORY.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SITE_NORMAL_ORGANIZATION_RM_INVENTORY)

sqlg_jobs.SDM_SITE_BU_BUFFER.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SITE_BU_BUFFER)

sqlg_jobs.SDM_SITE_CUSTOMER_LIABILITY_WH.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SITE_CUSTOMER_LIABILITY_WH)

sqlg_jobs.SDM_SITE_ERP_WH.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SITE_ERP_WH)

sqlg_jobs.SDM_FORECAST_CHANGE_REASON.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_FORECAST_CHANGE_REASON)

sqlg_jobs.SDM_SITE_INVENTORY_ANALYSIS.dag=D_SDM_SCM
D_STG_INITxSYS_STS_STGxD_SDM_SCM.set_downstream(sqlg_jobs.SDM_SITE_INVENTORY_ANALYSIS)

D_SDM_QAM = airflow.DAG(    "D_SDM_QAM",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_ODS_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_QAM"
D_STG_INITxSYS_STS_STGxD_ODS_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_SCM"
D_STG_INITxSYS_STS_STGxD_SDM_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_QAM"
D_STG_INITxSYS_STS_STGxD_SDM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_QAM"
D_STG_INITxSYS_STS_STGxD_DM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs.SDM_MATERIAL_CATEGORY_QA.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MATERIAL_CATEGORY_QA)

sqlg_jobs.SDM_PRODUCT_TYPE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_PRODUCT_TYPE)

sqlg_jobs.SDM_MODULE_TYPE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MODULE_TYPE)

sqlg_jobs.SDM_PRODUCT_DEVELOPMENT_TYPE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_PRODUCT_DEVELOPMENT_TYPE)

sqlg_jobs.SDM_MATERIAL_DEFECT_MODE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MATERIAL_DEFECT_MODE)

sqlg_jobs.SDM_CATEGORY.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CATEGORY)

sqlg_jobs.SDM_QA_RESULT.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_QA_RESULT)

sqlg_jobs.SDM_C_FLOW_DEVELOPMENT_STAGE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_C_FLOW_DEVELOPMENT_STAGE)

sqlg_jobs.SDM_C_FLOW_DEVELOPMENT_DERI.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_C_FLOW_DEVELOPMENT_DERI)

sqlg_jobs.SDM_CONTROL_STATION.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CONTROL_STATION)

sqlg_jobs.SDM_CONTROL_THE_PROJECT.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CONTROL_THE_PROJECT)

sqlg_jobs.SDM_TURN_AROUND_TIME.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_TURN_AROUND_TIME)

sqlg_jobs.SDM_RMA_CASE_STATUS.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_RMA_CASE_STATUS)

sqlg_jobs.SDM_PERSON_IN_CHARGE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_PERSON_IN_CHARGE)

sqlg_jobs.SDM_CLOSED_DAY_8D.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CLOSED_DAY_8D)

sqlg_jobs.SDM_TIER1.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_TIER1)

sqlg_jobs.SDM_SHIPPING_DATE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_SHIPPING_DATE)

sqlg_jobs.SDM_RETURN_SOURCE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_RETURN_SOURCE)

sqlg_jobs.SDM_WARRANTY_STATUS.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_WARRANTY_STATUS)

sqlg_jobs.SDM_INVENTORY_OWNER.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_INVENTORY_OWNER)

sqlg_jobs.SDM_MANUFACTURER.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MANUFACTURER)

sqlg_jobs.SDM_CAVITY_NO.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CAVITY_NO)

sqlg_jobs.SDM_CASE_CLOSE_STATUS.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CASE_CLOSE_STATUS)

sqlg_jobs.SDM_STATION.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_STATION)

sqlg_jobs.SDM_MO_NO.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MO_NO)

sqlg_jobs.SDM_MO_START_MONTH.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MO_START_MONTH)

sqlg_jobs.SDM_MO_PART_TYPE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MO_PART_TYPE)

sqlg_jobs.SDM_MP_APPROVE_DATE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MP_APPROVE_DATE)

sqlg_jobs.SDM_SR_NUMBER.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_SR_NUMBER)

sqlg_jobs.SDM_ATLO_FOR_MP.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_ATLO_FOR_MP)

sqlg_jobs.SDM_MP_FLAG.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MP_FLAG)

sqlg_jobs.SDM_PM.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_PM)

sqlg_jobs.SDM_CSD_REASON_PAY.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CSD_REASON_PAY)

sqlg_jobs.SDM_CSD_MATERIAL_SCRAP_COS.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CSD_MATERIAL_SCRAP_COS)

sqlg_jobs.SDM_CSD_CUSTOMER_PAID_SERV.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CSD_CUSTOMER_PAID_SERV)

sqlg_jobs.SDM_IQC_DAILY_INPUT_MANP_A.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_IQC_DAILY_INPUT_MANP_A)

sqlg_jobs.SDM_IQC_DAILY_INPUT_MANP.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_IQC_DAILY_INPUT_MANP)

sqlg_jobs.SDM_IQC_DAILY_TOTAL_INSP.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_IQC_DAILY_TOTAL_INSP)

sqlg_jobs.SDM_IQC_AVERAGE_INSPECTION.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_IQC_AVERAGE_INSPECTION)

sqlg_jobs.SDM_INCOMING_MATERIAL_REJECT_LOTS.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_INCOMING_MATERIAL_REJECT_LOTS)

sqlg_jobs.SDM_SUPPLIER_MATERIAL_PRODUC.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_SUPPLIER_MATERIAL_PRODUC)

sqlg_jobs.SDM_CUSTOMER_INSPECTION.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CUSTOMER_INSPECTION)

sqlg_jobs.SDM_CUSTOMER_COMPLAIN_CASES.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CUSTOMER_COMPLAIN_CASES)

sqlg_jobs.SDM_IN_PROCESS_QUALITY_CONTROL.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_IN_PROCESS_QUALITY_CONTROL)

sqlg_jobs.SDM_QUALITY_ALERT_CASES.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_QUALITY_ALERT_CASES)

sqlg_jobs.SDM_EQUIPMENT_ANOMALY_CASE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_EQUIPMENT_ANOMALY_CASE)

sqlg_jobs.SDM_FIXTURE_ANOMALY_CASES.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_FIXTURE_ANOMALY_CASES)

sqlg_jobs.SDM_EQUIPMENT_FIXTURE_ANOM.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_EQUIPMENT_FIXTURE_ANOM)

sqlg_jobs.SDM_FAULT_INJECTION_DR.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_FAULT_INJECTION_DR)

sqlg_jobs.SDM_Q_SCAN_DEFECT_RATE_DR.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_Q_SCAN_DEFECT_RATE_DR)

sqlg_jobs.SDM_FINAL_QUALITY_INSPECTI.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_FINAL_QUALITY_INSPECTI)

sqlg_jobs.SDM_FQC_LRR.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_FQC_LRR)

sqlg_jobs.SDM_QUALITY_HOLD_CASES.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_QUALITY_HOLD_CASES)

sqlg_jobs.SDM_CLOSE_WITHIN_SIPULATED.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CLOSE_WITHIN_SIPULATED)

sqlg_jobs.SDM_CUSTOMER_COMPLAIN_FOR.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CUSTOMER_COMPLAIN_FOR)

sqlg_jobs.SDM_ON_TIME_CLOSE_RATIO_FOR_WN.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_ON_TIME_CLOSE_RATIO_FOR_WN)

sqlg_jobs.SDM_CLOSE_WITHIN_14_DAYS_FO.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CLOSE_WITHIN_14_DAYS_FO)

sqlg_jobs.SDM_CUSTOMER_COMPLAIN_FOR_S.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CUSTOMER_COMPLAIN_FOR_S)

sqlg_jobs.SDM_CLOSE_WITHIN_14_DAYS_RATIO.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CLOSE_WITHIN_14_DAYS_RATIO)

sqlg_jobs.SDM_FIELD_DEFECT_QUANTITY.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_FIELD_DEFECT_QUANTITY)

sqlg_jobs.SDM_ON_SITE_REWORK_QUANTITY.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_ON_SITE_REWORK_QUANTITY)

sqlg_jobs.SDM_IN_WARRANTY_RETURN_QUANTITY.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_IN_WARRANTY_RETURN_QUANTITY)

sqlg_jobs.SDM_QUALITY_REJECT_QUANTITY.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_QUALITY_REJECT_QUANTITY)

sqlg_jobs.SDM_MODELS_WITH_MO_RECORDS.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_MODELS_WITH_MO_RECORDS)

sqlg_jobs.SDM_CSD_PLANNED_SHIPPING.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CSD_PLANNED_SHIPPING)

sqlg_jobs.SDM_ACTUAL_CALIBRATION.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_ACTUAL_CALIBRATION)

sqlg_jobs.SDM_PLANNED_CALIBRATION.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_PLANNED_CALIBRATION)

sqlg_jobs.SDM_CALIBRATION_COMPLETED_RATE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_CALIBRATION_COMPLETED_RATE)

sqlg_jobs.SDM_TICKET_TYPE.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_TICKET_TYPE)

sqlg_jobs.SDM_FINAL_QUALITY_INSPECT.dag=D_SDM_QAM
D_STG_INITxSYS_STS_STGxD_SDM_QAM.set_downstream(sqlg_jobs.SDM_FINAL_QUALITY_INSPECT)

D_DM_QAM = airflow.DAG(    "D_DM_QAM",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_ODS_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_QAM"
D_STG_INITxSYS_STS_STGxD_ODS_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_SCM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_SCM"
D_STG_INITxSYS_STS_STGxD_SDM_SCM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_QAM"
D_STG_INITxSYS_STS_STGxD_SDM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_QAM

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_QAM"
D_STG_INITxSYS_STS_STGxD_DM_QAM= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs.DIM_MATERIAL_CATEGORY_QA.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_MATERIAL_CATEGORY_QA)

sqlg_jobs.DIM_PRODUCT_TYPE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_PRODUCT_TYPE)

sqlg_jobs.DIM_MODULE_TYPE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_MODULE_TYPE)

sqlg_jobs.DIM_PRODUCT_DEVELOPMENT_TYPE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_PRODUCT_DEVELOPMENT_TYPE)

sqlg_jobs.DIM_MATERIAL_DEFECT_MODE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_MATERIAL_DEFECT_MODE)

sqlg_jobs.DIM_CATEGORY.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_CATEGORY)

sqlg_jobs.DIM_QA_RESULT.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_QA_RESULT)

sqlg_jobs.DIM_CONTROL_STATION.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_CONTROL_STATION)

sqlg_jobs.DIM_CONTROL_THE_PROJECT.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_CONTROL_THE_PROJECT)

sqlg_jobs.DIM_TURN_AROUND_TIME.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_TURN_AROUND_TIME)

sqlg_jobs.DIM_RMA_CASE_STATUS.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_RMA_CASE_STATUS)

sqlg_jobs.DIM_PERSON_IN_CHARGE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_PERSON_IN_CHARGE)

sqlg_jobs.DIM_CLOSED_DAY_8D.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_CLOSED_DAY_8D)

sqlg_jobs.DIM_TIER1.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_TIER1)

sqlg_jobs.DIM_SHIPPING_DATE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_SHIPPING_DATE)

sqlg_jobs.DIM_RETURN_SOURCE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_RETURN_SOURCE)

sqlg_jobs.DIM_WARRANTY_STATUS.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_WARRANTY_STATUS)

sqlg_jobs.DIM_INVENTORY_OWNER.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_INVENTORY_OWNER)

sqlg_jobs.DIM_CAVITY_NO.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_CAVITY_NO)

sqlg_jobs.DIM_CASE_CLOSE_STATUS.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_CASE_CLOSE_STATUS)

sqlg_jobs.DIM_STATION.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_STATION)

sqlg_jobs.DIM_C_FLOW_DEVELOPMENT_STAGE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_C_FLOW_DEVELOPMENT_STAGE)

sqlg_jobs.DIM_C_FLOW_DEVELOPMENT_DERI.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_C_FLOW_DEVELOPMENT_DERI)

sqlg_jobs.DIM_ATLO_FOR_MP.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_ATLO_FOR_MP)

sqlg_jobs.DIM_MP_FLAG.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_MP_FLAG)

sqlg_jobs.DIM_PM.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_PM)

sqlg_jobs.DIM_MO_NO.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_MO_NO)

sqlg_jobs.DIM_MO_START_MONTH.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_MO_START_MONTH)

sqlg_jobs.DIM_MP_APPROVE_DATE.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_MP_APPROVE_DATE)

sqlg_jobs.DIM_SR_NUMBER.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.DIM_SR_NUMBER)

sqlg_jobs.FCT_CSD_MATERIAL_SCRAP_COS.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CSD_MATERIAL_SCRAP_COS)

sqlg_jobs.FCT_CSD_CUSTOMER_PAID_SERV.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CSD_CUSTOMER_PAID_SERV)

sqlg_jobs.FCT_IQC_DAILY_INPUT_MANP.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_IQC_DAILY_INPUT_MANP)

sqlg_jobs.FCT_IQC_DAILY_TOTAL_INSP.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_IQC_DAILY_TOTAL_INSP)

sqlg_jobs.FCT_IQC_AVERAGE_INSPECTION.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_IQC_AVERAGE_INSPECTION)

sqlg_jobs.FCT_SUPPLIER_MATERIAL_PRODUC.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_SUPPLIER_MATERIAL_PRODUC)

sqlg_jobs.FCT_CUSTOMER_INSPECTION.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CUSTOMER_INSPECTION)

sqlg_jobs.FCT_CUSTOMER_COMPLAIN_CASES.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CUSTOMER_COMPLAIN_CASES)

sqlg_jobs.FCT_FAULT_INJECTION_DR.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_FAULT_INJECTION_DR)

sqlg_jobs.FCT_Q_SCAN_DEFECT_RATE_DR.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_Q_SCAN_DEFECT_RATE_DR)

sqlg_jobs.FCT_QUALITY_HOLD_CASES.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_QUALITY_HOLD_CASES)

sqlg_jobs.FCT_CLOSE_WITHIN_SIPULATED.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CLOSE_WITHIN_SIPULATED)

sqlg_jobs.FCT_CUSTOMER_COMPLAIN_FOR.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CUSTOMER_COMPLAIN_FOR)

sqlg_jobs.FCT_ON_TIME_CLOSE_RATIO_FOR_WN.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_ON_TIME_CLOSE_RATIO_FOR_WN)

sqlg_jobs.FCT_CLOSE_WITHIN_14_DAYS_FO.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CLOSE_WITHIN_14_DAYS_FO)

sqlg_jobs.FCT_CUSTOMER_COMPLAIN_FOR_S.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CUSTOMER_COMPLAIN_FOR_S)

sqlg_jobs.FCT_CLOSE_WITHIN_14_DAYS_RATIO.dag=D_DM_QAM
D_STG_INITxSYS_STS_STGxD_DM_QAM.set_downstream(sqlg_jobs.FCT_CLOSE_WITHIN_14_DAYS_RATIO)

