
ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 DISABLE CONSTRAINT SDM_PROD_DEV_MLST_DELAY_RATE_TP1_X;
TRUNCATE TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1;

INSERT /*+ append */ INTO SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 (
      BUSINESS_GROUP                          
      ,PROJECT_CODE                            
      ,MODEL                                   
      ,MANUFACTURING_PLANT                     
      ,MILESTONE                               
      ,ACTIVITY                                
      ,PROD_DEV_MLST_DELAY_RATE                
)
      SELECT
       SSCPDT.BUSINESS_GROUP              AS BUSINESS_GROUP
      ,MA.PROJECT_CODE                    AS PROJECT_CODE
      ,MA.MODEL                           AS MODEL
      ,MA.MANUFACTURING_PLANT             AS MANUFACTURING_PLANT
      ,MA.MILESTONE                       AS MILESTONE
      ,MA.ACTIVITY                        AS ACTIVITY
      ,AVG((SSCPDT.CDOC_PLANNED_DEV_TIME - MA.CDOC_DELAY_TIME)/SSCPDT.CDOC_PLANNED_DEV_TIME)      AS PROD_DEV_MLST_DELAY_RATE
FROM SDM.SDM_CDOC_DELAY_TIME MA  
LEFT JOIN SDM.SDM_CDOC_PLANNED_DEV_TIME SSCPDT ON MA.BUSINESS_GROUP=SSCPDT.BUSINESS_GROUP  and MA.PROJECT_CODE=SSCPDT.PROJECT_CODE and MA.MODEL=SSCPDT.MODEL and MA.MANUFACTURING_PLANT=SSCPDT.MANUFACTURING_PLANT and MA.MILESTONE=SSCPDT.MILESTONE and MA.ACTIVITY=SSCPDT.ACTIVITY
WHERE SSCPDT.CDOC_PLANNED_DEV_TIME>0
GROUP BY SSCPDT.BUSINESS_GROUP,MA.PROJECT_CODE,MA.MODEL,MA.MANUFACTURING_PLANT,MA.MILESTONE,MA.ACTIVITY
;



ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 ENABLE CONSTRAINT SDM_PROD_DEV_MLST_DELAY_RATE_TP1_X EXCEPTIONS INTO SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TPX;

ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE DISABLE CONSTRAINT SDM_PROD_DEV_MLST_DELAY_RATE_X;
TRUNCATE TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE;

INSERT /*+ append */ INTO SDM.SDM_PROD_DEV_MLST_DELAY_RATE (
      BUSINESS_GROUP                          
      ,PROJECT_CODE                            
      ,MODEL                                   
      ,MANUFACTURING_PLANT                     
      ,MILESTONE                               
      ,ACTIVITY                                
      ,PROD_DEV_MLST_DELAY_RATE                
      ,DATA_DATE                               
      ,TBL_UPD_TIME                            
      ,TBL_UPD_SRC                             
) 
      SELECT
      MA.BUSINESS_GROUP                       
      ,MA.PROJECT_CODE                         
      ,MA.MODEL                                
      ,MA.MANUFACTURING_PLANT                  
      ,MA.MILESTONE                            
      ,MA.ACTIVITY                             
      ,MA.PROD_DEV_MLST_DELAY_RATE             
      ,'20201108'                            
      ,CURRENT_DATE                         
      ,'SDM_CDOC_DELAY_TIME'                          
FROM SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 MA ; 



ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE ENABLE CONSTRAINT SDM_PROD_DEV_MLST_DELAY_RATE_X EXCEPTIONS INTO SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TPX;

-- Update statistics
CALL DBMS_STATS.GATHER_TABLE_STATS('SDM','SDM_PROD_DEV_MLST_DELAY_RATE');


