
CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_PROD_DEV_MLST_DELAY_RATE');
CREATE TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE (
       BUSINESS_GROUP                          VARCHAR2(30) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(30) NOT NULL
      ,MODEL                                   VARCHAR2(30) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,MILESTONE                               NUMBER(1, 0) NOT NULL
      ,ACTIVITY                                VARCHAR2(765) NOT NULL
      ,PROD_DEV_MLST_DELAY_RATE                NUMBER
      ,DATA_DATE                               VARCHAR2(8)
      ,TBL_UPD_TIME                            DATE
      ,TBL_UPD_SRC                             VARCHAR2(100)
);

ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE nologging;

--PK Create Script
ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE ADD CONSTRAINT SDM_PROD_DEV_MLST_DELAY_RATE_X PRIMARY KEY(BUSINESS_GROUP,PROJECT_CODE,MODEL,MANUFACTURING_PLANT,MILESTONE,ACTIVITY) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE IS '產品開發階段專案延遲比率';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.BUSINESS_GROUP IS '標準-事業群';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.PROJECT_CODE IS '專案代碼';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.MODEL IS 'Model';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.MANUFACTURING_PLANT IS '標準-製造廠';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.MILESTONE IS 'MILESTONE';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.ACTIVITY IS 'ACTIVITY';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.PROD_DEV_MLST_DELAY_RATE IS '產品開發階段專案延遲比率';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.DATA_DATE IS 'DataDate';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.TBL_UPD_TIME IS 'Updated Time';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE.TBL_UPD_SRC IS 'Updated Source';

CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_PROD_DEV_MLST_DELAY_RATE_TPX');
CREATE TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TPX AS SELECT * FROM SQLEXT.EXCEPTIONS WHERE 1=2
;




CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_PROD_DEV_MLST_DELAY_RATE_TP1');
CREATE TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 (
       BUSINESS_GROUP                          VARCHAR2(30) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(30) NOT NULL
      ,MODEL                                   VARCHAR2(30) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,MILESTONE                               NUMBER(1, 0) NOT NULL
      ,ACTIVITY                                VARCHAR2(765) NOT NULL
      ,PROD_DEV_MLST_DELAY_RATE                NUMBER
);

ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 nologging;

--PK Create Script
ALTER TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 ADD CONSTRAINT SDM_PROD_DEV_MLST_DELAY_RATE_TP1_X PRIMARY KEY(BUSINESS_GROUP,PROJECT_CODE,MODEL,MANUFACTURING_PLANT,MILESTONE,ACTIVITY) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1 IS '產品開發階段專案延遲比率暫存檔';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1.BUSINESS_GROUP IS '標準-事業群';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1.PROJECT_CODE IS '專案代碼';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1.MODEL IS 'Model';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1.MANUFACTURING_PLANT IS '標準-製造廠';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1.MILESTONE IS 'MILESTONE';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1.ACTIVITY IS 'ACTIVITY';
COMMENT ON COLUMN SDM.SDM_PROD_DEV_MLST_DELAY_RATE_TP1.PROD_DEV_MLST_DELAY_RATE IS '產品開發階段專案延遲比率';



