
CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_CDOC_PLANNED_DEV_TIME');
CREATE TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME (
       ACTIVITY                                VARCHAR2(765) NOT NULL
      ,MILESTONE                               NUMBER(1, 0) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(50) NOT NULL
      ,BUSINESS_GROUP                          VARCHAR2(50) NOT NULL
      ,MODEL                                   VARCHAR2(50) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,CDOC_PLANNED_DEV_TIME                   NUMBER
      ,DATA_DATE                               VARCHAR2(8)
      ,TBL_UPD_TIME                            DATE
      ,TBL_UPD_SRC                             VARCHAR2(100)
);

ALTER TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME nologging;

--PK Create Script
ALTER TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME ADD CONSTRAINT SDM_CDOC_PLANNED_DEV_TIME_X PRIMARY KEY(ACTIVITY,MILESTONE,PROJECT_CODE,BUSINESS_GROUP,MODEL,MANUFACTURING_PLANT) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME IS '產品開發階段專案規劃時間';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.ACTIVITY IS 'ACTIVITY';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.MILESTONE IS 'MILESTONE';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.PROJECT_CODE IS 'PROJECT_CODE';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.BUSINESS_GROUP IS 'BUSINESS_GROUP';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.MODEL IS 'MODEL';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.MANUFACTURING_PLANT IS '標準-製造廠';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.CDOC_PLANNED_DEV_TIME IS '產品開發階段專案規劃時間';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.DATA_DATE IS 'DataDate';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.TBL_UPD_TIME IS 'Updated Time';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME.TBL_UPD_SRC IS 'Updated Source';

CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_CDOC_PLANNED_DEV_TIME_TPX');
CREATE TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME_TPX AS SELECT * FROM SQLEXT.EXCEPTIONS WHERE 1=2
;




CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_CDOC_PLANNED_DEV_TIME_TP1');
CREATE TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1 (
       ACTIVITY                                VARCHAR2(765) NOT NULL
      ,MILESTONE                               NUMBER(1, 0) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(50) NOT NULL
      ,BUSINESS_GROUP                          VARCHAR2(50) NOT NULL
      ,MODEL                                   VARCHAR2(50) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,CDOC_PLANNED_DEV_TIME                   NUMBER
);

ALTER TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1 nologging;

--PK Create Script
ALTER TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1 ADD CONSTRAINT SDM_CDOC_PLANNED_DEV_TIME_TP1_X PRIMARY KEY(ACTIVITY,MILESTONE,PROJECT_CODE,BUSINESS_GROUP,MODEL,MANUFACTURING_PLANT) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1 IS '產品開發階段專案規劃時間暫存檔';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1.ACTIVITY IS 'ACTIVITY';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1.MILESTONE IS 'MILESTONE';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1.PROJECT_CODE IS 'PROJECT_CODE';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1.BUSINESS_GROUP IS 'BUSINESS_GROUP';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1.MODEL IS 'MODEL';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1.MANUFACTURING_PLANT IS '標準-製造廠';
COMMENT ON COLUMN SDM.SDM_CDOC_PLANNED_DEV_TIME_TP1.CDOC_PLANNED_DEV_TIME IS '產品開發階段專案規劃時間';



