
CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_TOOLING_TOTAL_EXPENSE');
CREATE TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE (
       BUSINESS_GROUP                          VARCHAR2(30) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(30) NOT NULL
      ,MODEL                                   VARCHAR2(30) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,TOOLING_TOTAL_EXPENSE                   VARCHAR2(30)
      ,DATA_DATE                               VARCHAR2(8)
      ,TBL_UPD_TIME                            DATE
      ,TBL_UPD_SRC                             VARCHAR2(100)
);

ALTER TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE nologging;

--PK Create Script
ALTER TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE ADD CONSTRAINT SDM_TOOLING_TOTAL_EXPENSE_X PRIMARY KEY(BUSINESS_GROUP,PROJECT_CODE,MODEL,MANUFACTURING_PLANT) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE IS '家ㄣや羆禣ノ (CNC Samples)';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.BUSINESS_GROUP IS '夹非-ㄆ穨竤';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.PROJECT_CODE IS '盡絏';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.MODEL IS 'Model';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.MANUFACTURING_PLANT IS '夹非-籹硑紅';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.TOOLING_TOTAL_EXPENSE IS '家ㄣや羆禣ノ (CNC Samples)';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.DATA_DATE IS 'DataDate';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.TBL_UPD_TIME IS 'Updated Time';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE.TBL_UPD_SRC IS 'Updated Source';

CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_TOOLING_TOTAL_EXPENSE_TPX');
CREATE TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE_TPX AS SELECT * FROM SQLEXT.EXCEPTIONS WHERE 1=2
;




CALL SQLEXT.SP_DROP_IF_EXISTS ('SDM', 'SDM_TOOLING_TOTAL_EXPENSE_TP1');
CREATE TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1 (
       BUSINESS_GROUP                          VARCHAR2(30) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(30) NOT NULL
      ,MODEL                                   VARCHAR2(30) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,TOOLING_TOTAL_EXPENSE                   VARCHAR2(30)
);

ALTER TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1 nologging;

--PK Create Script
ALTER TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1 ADD CONSTRAINT SDM_TOOLING_TOTAL_EXPENSE_TP1_X PRIMARY KEY(BUSINESS_GROUP,PROJECT_CODE,MODEL,MANUFACTURING_PLANT) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1 IS '家ㄣや羆禣ノ (CNC Samples)既郎';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1.BUSINESS_GROUP IS '夹非-ㄆ穨竤';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1.PROJECT_CODE IS '盡絏';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1.MODEL IS 'Model';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1.MANUFACTURING_PLANT IS '夹非-籹硑紅';
COMMENT ON COLUMN SDM.SDM_TOOLING_TOTAL_EXPENSE_TP1.TOOLING_TOTAL_EXPENSE IS '家ㄣや羆禣ノ (CNC Samples)';



