
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2018/08/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
import sqlg_jobs 

#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams

def f_SYS_STS_STG():
    logging.info('Control flow: STAGE status ')

args = {
    'owner': 'airflow',
    'start_date': airflow.utils.dates.days_ago(7),
    'provide_context': True
}

tmpl_search_path = Variable.get("sql_path")

my_taskid = 'SYS_STS_STG'
D_STG_INIT = airflow.DAG(
    'D_STG_INIT',
    schedule_interval=timedelta(1),
    default_args=args,
    template_searchpath=tmpl_search_path,    
    max_active_runs=1)

SYS_STS_STG = PythonOperator(task_id=my_taskid,
                    python_callable=f_SYS_STS_STG,
                    provide_context=False,
                    dag=D_STG_INIT)

my_taskid = 'D_STG_INITxSYS_STS_STG'                    
D_STG_INITxSYS_STS_STG = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_STG_INIT',
    external_task_id='SYS_STS_STG',
    execution_delta=None,  # Same day as today
    )


my_taskid = 'D_STG_INITxSYS_STS_STGxD_ODS_PRD'                    
D_STG_INITxSYS_STS_STGxD_ODS_PRD = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_STG_INIT',
    external_task_id='SYS_STS_STG',
    execution_delta=None,  # Same day as today
    )
my_taskid = 'D_STG_INITxSYS_STS_STGxD_SDM_PRD'                    
D_STG_INITxSYS_STS_STGxD_SDM_PRD = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_STG_INIT',
    external_task_id='SYS_STS_STG',
    execution_delta=None,  # Same day as today
    )

my_taskid = 'D_ODS_PRDxXXPLM_MODELxD_SDM_PRD'                    
D_ODS_PRDxXXPLM_MODELxD_SDM_PRD = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_ODS_PRD',
    external_task_id='XXPLM_MODEL',
    execution_delta=None,  # Same day as today
    )
my_taskid = 'D_ODS_PRDxMTL_SYSTEM_ITEMS_BxD_SDM_PRD'                    
D_ODS_PRDxMTL_SYSTEM_ITEMS_BxD_SDM_PRD = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_ODS_PRD',
    external_task_id='MTL_SYSTEM_ITEMS_B',
    execution_delta=None,  # Same day as today
    )




# Flow dag    
# DB_NAME = 'DWH'    
D_ODS_PRD = airflow.DAG(    "D_ODS_PRD",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(7),    
    max_active_runs=1)

sqlg_jobs.MTL_SYSTEM_ITEMS_B.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MTL_SYSTEM_ITEMS_B)

sqlg_jobs.FND_COLUMNS.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.FND_COLUMNS)

sqlg_jobs.FND_LOOKUP_TYPES.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.FND_LOOKUP_TYPES)

sqlg_jobs.FND_LOOKUP_VALUES.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.FND_LOOKUP_VALUES)

sqlg_jobs.FND_TABLES.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.FND_TABLES)

sqlg_jobs.MTL_CATEGORIES_B.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MTL_CATEGORIES_B)

sqlg_jobs.MTL_CATEGORY_SETS_B.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MTL_CATEGORY_SETS_B)

sqlg_jobs.MTL_CUSTOMER_ITEMS.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MTL_CUSTOMER_ITEMS)

sqlg_jobs.MTL_ITEM_CATALOG_GROUPS_B.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MTL_ITEM_CATALOG_GROUPS_B)

sqlg_jobs.MTL_ITEM_CATEGORIES.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MTL_ITEM_CATEGORIES)

sqlg_jobs.MTL_ITEM_STATUS_TL.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MTL_ITEM_STATUS_TL)

sqlg_jobs.MV_PROJECT_ACTIVITY.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MV_PROJECT_ACTIVITY)

sqlg_jobs.MV_XXPLM_CFDMETADATA.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MV_XXPLM_CFDMETADATA)

sqlg_jobs.MV_XXPLM_EC.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MV_XXPLM_EC)

sqlg_jobs.PRJ_WORKTIMEDATA.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.PRJ_WORKTIMEDATA)

sqlg_jobs.XXPLM_MODEL.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.XXPLM_MODEL)

sqlg_jobs.XXPLM_PROJECT.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.XXPLM_PROJECT)

sqlg_jobs.XXPLM_TFD.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.XXPLM_TFD)

sqlg_jobs.Z_CDOCUMENT_CHECKING_RULE.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.Z_CDOCUMENT_CHECKING_RULE)

sqlg_jobs.MV_XXPLM_MODEL_CHECKRULE_V.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.MV_XXPLM_MODEL_CHECKRULE_V)

sqlg_jobs.XXPLM_EC_CHANGE_TYPE.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.XXPLM_EC_CHANGE_TYPE)

sqlg_jobs.NSP_REQ_HEADERS.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.NSP_REQ_HEADERS)

sqlg_jobs.NSP_REQ_LINES.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.NSP_REQ_LINES)

sqlg_jobs.PCS_HEADER.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.PCS_HEADER)

sqlg_jobs.PCS_LINEEE.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.PCS_LINEEE)

sqlg_jobs.BTMS_EXPENSEPROJECT.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs.BTMS_EXPENSEPROJECT)

D_SDM_PRD = airflow.DAG(    "D_SDM_PRD",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(7),    
    max_active_runs=1)

sqlg_jobs.SDM_TEMPLATE_PRD.dag=D_SDM_PRD
D_ODS_PRDxXXPLM_MODELxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_TEMPLATE_PRD)

sqlg_jobs.SDM_PLM_CATEGORY.dag=D_SDM_PRD
D_ODS_PRDxXXPLM_MODELxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_PLM_CATEGORY)

sqlg_jobs.SDM_ITEM.dag=D_SDM_PRD
D_ODS_PRDxMTL_SYSTEM_ITEMS_BxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_ITEM)

# sqlg_jobs.SDM_ECN_REASON.dag=D_SDM_PRD
# D_ODS_PRDxXXPLM_EC_CHANGE_TYPExD_SDM_PRD.set_downstream(sqlg_jobs.SDM_ECN_REASON)

# sqlg_jobs.SDM_XXPLM_EC.dag=D_SDM_PRD
# D_ODS_PRDxMV_XXPLM_ECxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_XXPLM_EC)

# sqlg_jobs.SDM_ECN_CASE_AFTER_MP.dag=D_SDM_PRD
# SDM_XXPLM_EC.set_downstream(SDM_ECN_CASE_AFTER_MP)
# D_ODS_PRDxXXPLM_MODELxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_ECN_CASE_AFTER_MP)
# D_STG_INITxSYS_STS_STGxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_ECN_CASE_AFTER_MP)

# sqlg_jobs.SDM_CDOC_COMPLETION_RATE.dag=D_SDM_PRD
# SDM_UPLOAD_CDOC_COUNT.set_downstream(SDM_CDOC_COMPLETION_RATE)
# SDM_TOTAL_CDOC_COUNT.set_downstream(SDM_CDOC_COMPLETION_RATE)

# sqlg_jobs.SDM_UPLOAD_CDOC_COUNT.dag=D_SDM_PRD
# D_ODS_PRDxZ_CDOCUMENT_CHECKING_RULExD_SDM_PRD.set_downstream(sqlg_jobs.SDM_UPLOAD_CDOC_COUNT)
# D_ODS_PRDxMV_XXPLM_CFDMETADATAxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_UPLOAD_CDOC_COUNT)

# sqlg_jobs.SDM_TOTAL_CDOC_COUNT.dag=D_SDM_PRD
# SDM_UPLOAD_CDOC_COUNT.set_downstream(SDM_TOTAL_CDOC_COUNT)

# sqlg_jobs.SDM_PROJECT_CODE.dag=D_SDM_PRD
# D_ODS_PRDxXXPLM_PROJECTxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_PROJECT_CODE)

# sqlg_jobs.SDM_TOOLING_TOTAL_EXPENSE.dag=D_SDM_PRD
# D_ODS_PRDxNSP_REQ_HEADERSxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_TOOLING_TOTAL_EXPENSE)
# D_SDM_FINxSDM_MANUFACTURING_PLANTxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_TOOLING_TOTAL_EXPENSE)
# SDM_PROJECT_CODE.set_downstream(SDM_TOOLING_TOTAL_EXPENSE)

# sqlg_jobs.SDM_DMST_AND_INTL_TRAVEL_EXP.dag=D_SDM_PRD
# D_ODS_PRDxPCS_HEADERxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_DMST_AND_INTL_TRAVEL_EXP)
# D_ODS_PRDxPCS_LINEEExD_SDM_PRD.set_downstream(sqlg_jobs.SDM_DMST_AND_INTL_TRAVEL_EXP)
# D_ODS_PRDxBTMS_EXPENSEPROJECTxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_DMST_AND_INTL_TRAVEL_EXP)

# sqlg_jobs.SDM_TESTING_EXPENSE.dag=D_SDM_PRD
# SDM_CTF_EXPENSE.set_downstream(SDM_TESTING_EXPENSE)
# SDM_EQT_EXPENSE.set_downstream(SDM_TESTING_EXPENSE)

# sqlg_jobs.SDM_CTF_EXPENSE.dag=D_SDM_PRD
# D_ODS_PRDxNSP_REQ_HEADERSxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_CTF_EXPENSE)
# D_SDM_FINxSDM_MANUFACTURING_PLANTxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_CTF_EXPENSE)
# SDM_PROJECT_CODE.set_downstream(SDM_CTF_EXPENSE)

# sqlg_jobs.SDM_EQT_EXPENSE.dag=D_SDM_PRD
# D_ODS_PRDxNSP_REQ_HEADERSxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_EQT_EXPENSE)
# D_SDM_FINxSDM_MANUFACTURING_PLANTxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_EQT_EXPENSE)
# SDM_PROJECT_CODE.set_downstream(SDM_EQT_EXPENSE)

# sqlg_jobs.SDM_EPR_MFG_SAMPLE_BUILD_EXP.dag=D_SDM_PRD
# D_ODS_PRDxNSP_REQ_HEADERSxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_EPR_MFG_SAMPLE_BUILD_EXP)
# D_SDM_FINxSDM_MANUFACTURING_PLANTxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_EPR_MFG_SAMPLE_BUILD_EXP)
# SDM_PROJECT_CODE.set_downstream(SDM_EPR_MFG_SAMPLE_BUILD_EXP)

# sqlg_jobs.SDM_CDOC_PLANNED_DEV_TIME.dag=D_SDM_PRD
# D_ODS_PRDxMV_PROJECT_ACTIVITYxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_CDOC_PLANNED_DEV_TIME)
# D_ODS_PRDxXXPLM_MODELxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_CDOC_PLANNED_DEV_TIME)

# sqlg_jobs.SDM_PROD_DEV_MLST_DELAY_RATE.dag=D_SDM_PRD
# SDM_CDOC_PLANNED_DEV_TIME.set_downstream(SDM_PROD_DEV_MLST_DELAY_RATE)
# SDM_CDOC_DELAY_TIME.set_downstream(SDM_PROD_DEV_MLST_DELAY_RATE)

# sqlg_jobs.SDM_CDOC_DELAY_TIME.dag=D_SDM_PRD
# D_ODS_PRDxMV_PROJECT_ACTIVITYxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_CDOC_DELAY_TIME)
# D_ODS_PRDxXXPLM_MODELxD_SDM_PRD.set_downstream(sqlg_jobs.SDM_CDOC_DELAY_TIME)

