
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/11/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import re
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams

# XSLT:loop: declaration: START{
import sqlg_jobs_GBD


args = {
    "owner": "JESSEWEI",
    'start_date': airflow.utils.dates.days_ago(1),
    'provide_context': True
}	
# XSLT:loop: declaration: END}

ExternalTaskSensor.ui_color = 'white'
ExternalTaskSensor.ui_fgcolor = 'blue'

tmpl_search_path = Variable.get("sql_path")
	

# XSLT:loop: JOB_FLOW_NAME: START{
job_flow_name = "D_ODS_GBD_SRC"
if job_flow_name == 'I_SDM_CMN':
    data_stage = ['ODS']
else:
    data_stage = re.findall(r"_(.*?)_","D_ODS_GBD_SRC")
D_ODS_GBD_SRC = airflow.DAG(
    "D_ODS_GBD_SRC",
    tags=["GBD", data_stage[0]],
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)
job_flow_name = "D_SDM_GBD"
if job_flow_name == 'I_SDM_CMN':
    data_stage = ['ODS']
else:
    data_stage = re.findall(r"_(.*?)_","D_SDM_GBD")
D_SDM_GBD = airflow.DAG(
    "D_SDM_GBD",
    tags=["GBD", data_stage[0]],
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)
job_flow_name = "D_DM_GBD"
if job_flow_name == 'I_SDM_CMN':
    data_stage = ['ODS']
else:
    data_stage = re.findall(r"_(.*?)_","D_DM_GBD")
D_DM_GBD = airflow.DAG(
    "D_DM_GBD",
    tags=["GBD", data_stage[0]],
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)

# XSLT:loop: JOB_FLOW_NAME: END}

# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: External:START{{

my_taskid = "D_ODS_GBD_SRCxD_STG_INIT__SYS_STS_STG"
D_ODS_GBD_SRCxD_STG_INIT__SYS_STS_STG= ExternalTaskSensor(
#    schedule_interval=None,
    pool = "sensor_pool",
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    mode="reschedule",
    dag=D_ODS_GBD_SRC,
#    execution_delta=None,  # Same day as today
)

my_taskid = "D_SDM_GBDxD_STG_INIT__SYS_STS_STG"
D_SDM_GBDxD_STG_INIT__SYS_STS_STG= ExternalTaskSensor(
#    schedule_interval=None,
    pool = "sensor_pool",
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    mode="reschedule",
    dag=D_SDM_GBD,
#    execution_delta=None,  # Same day as today
)

my_taskid = "D_DM_GBDxD_STG_INIT__SYS_STS_STG"
D_DM_GBDxD_STG_INIT__SYS_STS_STG= ExternalTaskSensor(
#    schedule_interval=None,
    pool = "sensor_pool",
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    mode="reschedule",
    dag=D_DM_GBD,
#    execution_delta=None,  # Same day as today
)
	
# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: External: END}}


# XSLT:loop: JOB_FLOW_NAME: START{


# 	XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{
sqlg_jobs_GBD.GBD_RFQ_TRACKER.dag=D_ODS_GBD_SRC
D_ODS_GBD_SRCxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.GBD_RFQ_TRACKER)
sqlg_jobs_GBD.GBD_REVENUE.dag=D_ODS_GBD_SRC
D_ODS_GBD_SRCxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.GBD_REVENUE)


# 	XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{
sqlg_jobs_GBD.REF_RFQ_STAGE.dag=D_SDM_GBD
D_SDM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.REF_RFQ_STAGE)
sqlg_jobs_GBD.REF_PIPELINE_STATUS.dag=D_SDM_GBD
D_SDM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.REF_PIPELINE_STATUS)
sqlg_jobs_GBD.REF_PIPELINE_RESULT.dag=D_SDM_GBD
D_SDM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.REF_PIPELINE_RESULT)
sqlg_jobs_GBD.REF_PROGRESSION_STATUS.dag=D_SDM_GBD
D_SDM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.REF_PROGRESSION_STATUS)
sqlg_jobs_GBD.REF_BMC.dag=D_SDM_GBD
D_SDM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.REF_BMC)
sqlg_jobs_GBD.SDM_REVENUE_HIT_RATE.dag=D_SDM_GBD
D_SDM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.SDM_REVENUE_HIT_RATE)
sqlg_jobs_GBD.SDM_FORECAST_PROJECT_REV.dag=D_SDM_GBD
D_SDM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.SDM_FORECAST_PROJECT_REV)


# 	XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{
sqlg_jobs_GBD.FCT_REVENUE_HIT_RATE.dag=D_DM_GBD
D_DM_GBDxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_GBD.FCT_REVENUE_HIT_RATE)
