
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/10/04
# Impact        : Jobs generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow.operators.bash_operator import BashOperator
from airflow.contrib.sensors.file_sensor import FileSensor


from airflow import models
from airflow.models import Variable


from acme.operators.sqlg_oracle import OracleOperatorWithTemplatedParams
from airflow.operators.oracle_operator import OracleOperator
# DB_NAME = 'DWH'

# JOB_TYPE=ODS-MAIN
my_taskid = "GBD_RFQ_TRACKER"
GBD_RFQ_TRACKER = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "GBD_REVENUE"
GBD_REVENUE = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "MV_HR_EMPMSF_H"
MV_HR_EMPMSF_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "MV_HR_EMPMSF_CN_H"
MV_HR_EMPMSF_CN_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "MV_HR_EMPMSF_VN_H"
MV_HR_EMPMSF_VN_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "HR_DEPMSF_H"
HR_DEPMSF_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "HR_DEPMSF_CN_H"
HR_DEPMSF_CN_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "HR_DEPMSF_VN_H"
HR_DEPMSF_VN_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "REF_RFQ_STAGE"
REF_RFQ_STAGE = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "REF_PIPELINE_STATUS"
REF_PIPELINE_STATUS = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "REF_PIPELINE_RESULT"
REF_PIPELINE_RESULT = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "REF_PROGRESSION_STATUS"
REF_PROGRESSION_STATUS = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "REF_BMC"
REF_BMC = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "SDM_REVENUE_HIT_RATE"
SDM_REVENUE_HIT_RATE = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "SDM_FORECAST_PROJECT_REV"
SDM_FORECAST_PROJECT_REV = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "SDM_DEPARTMENT_H"
SDM_DEPARTMENT_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "SDM_EMPLOYEE_H"
SDM_EMPLOYEE_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "FCT_REVENUE_HIT_RATE"
FCT_REVENUE_HIT_RATE = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        "); End;"
    )
