
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2018/08/04
# Impact        : Jobs generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable

from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams


# DB_NAME = 'DWH'

my_taskid = "MTL_SYSTEM_ITEMS_B"
MTL_SYSTEM_ITEMS_B = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "FND_COLUMNS"
FND_COLUMNS = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "FND_LOOKUP_TYPES"
FND_LOOKUP_TYPES = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "FND_LOOKUP_VALUES"
FND_LOOKUP_VALUES = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "FND_TABLES"
FND_TABLES = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MTL_CATEGORIES_B"
MTL_CATEGORIES_B = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MTL_CATEGORY_SETS_B"
MTL_CATEGORY_SETS_B = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MTL_CUSTOMER_ITEMS"
MTL_CUSTOMER_ITEMS = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MTL_ITEM_CATALOG_GROUPS_B"
MTL_ITEM_CATALOG_GROUPS_B = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MTL_ITEM_CATEGORIES"
MTL_ITEM_CATEGORIES = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MTL_ITEM_STATUS_TL"
MTL_ITEM_STATUS_TL = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MV_PROJECT_ACTIVITY"
MV_PROJECT_ACTIVITY = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MV_XXPLM_CFDMETADATA"
MV_XXPLM_CFDMETADATA = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MV_XXPLM_EC"
MV_XXPLM_EC = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "PRJ_WORKTIMEDATA"
PRJ_WORKTIMEDATA = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "XXPLM_MODEL"
XXPLM_MODEL = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "XXPLM_PROJECT"
XXPLM_PROJECT = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "XXPLM_TFD"
XXPLM_TFD = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "Z_CDOCUMENT_CHECKING_RULE"
Z_CDOCUMENT_CHECKING_RULE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "MV_XXPLM_MODEL_CHECKRULE_V"
MV_XXPLM_MODEL_CHECKRULE_V = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "XXPLM_EC_CHANGE_TYPE"
XXPLM_EC_CHANGE_TYPE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "NSP_REQ_HEADERS"
NSP_REQ_HEADERS = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "NSP_REQ_LINES"
NSP_REQ_LINES = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "PCS_HEADER"
PCS_HEADER = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "PCS_LINEEE"
PCS_LINEEE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "BTMS_EXPENSEPROJECT"
BTMS_EXPENSEPROJECT = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_EMPLOYEE_H"
SDM_EMPLOYEE_H = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_TEMPLATE_PRD"
SDM_TEMPLATE_PRD = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_PLM_CATEGORY"
SDM_PLM_CATEGORY = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_ITEM"
SDM_ITEM = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_ECN_REASON"
SDM_ECN_REASON = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_XXPLM_EC"
SDM_XXPLM_EC = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_ECN_CASE_AFTER_MP"
SDM_ECN_CASE_AFTER_MP = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_CDOC_COMPLETION_RATE"
SDM_CDOC_COMPLETION_RATE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_UPLOAD_CDOC_COUNT"
SDM_UPLOAD_CDOC_COUNT = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_TOTAL_CDOC_COUNT"
SDM_TOTAL_CDOC_COUNT = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_PROJECT_CODE"
SDM_PROJECT_CODE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_TOOLING_TOTAL_EXPENSE"
SDM_TOOLING_TOTAL_EXPENSE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_DMST_AND_INTL_TRAVEL_EXP"
SDM_DMST_AND_INTL_TRAVEL_EXP = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_TESTING_EXPENSE"
SDM_TESTING_EXPENSE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_CTF_EXPENSE"
SDM_CTF_EXPENSE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_EQT_EXPENSE"
SDM_EQT_EXPENSE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_EPR_MFG_SAMPLE_BUILD_EXP"
SDM_EPR_MFG_SAMPLE_BUILD_EXP = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_CDOC_PLANNED_DEV_TIME"
SDM_CDOC_PLANNED_DEV_TIME = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_PROD_DEV_MLST_DELAY_RATE"
SDM_PROD_DEV_MLST_DELAY_RATE = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


my_taskid = "SDM_CDOC_DELAY_TIME"
SDM_CDOC_DELAY_TIME = PostgresOperatorWithTemplatedParams(
    task_id=my_taskid,
    postgres_conn_id='postgres_dwh',
#    sql=DB_NAME + '/' + my_taskid + '/' + my_taskid + '.sql',
    sql=my_taskid + '/' + my_taskid + '.sql',
    parameters={"window_start_date": "{{ ds }}", "window_end_date": "{{ tomorrow_ds }}"},
    start_date=airflow.utils.dates.days_ago(7),
    pool='postgres_dwh')


