
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/10/04
# Impact        : Jobs generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow.operators.bash_operator import BashOperator
from airflow.contrib.sensors.file_sensor import FileSensor


from airflow import models
from airflow.models import Variable


from acme.operators.sqlg_oracle import OracleOperatorWithTemplatedParams
from airflow.operators.oracle_operator import OracleOperator
# DB_NAME = 'DWH'

# JOB_TYPE=ODS-MAIN
my_taskid = "SDM_CODE"
SDM_CODE = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ",${END_DT_CHAR}"+
        "); End;"
    )

# JOB_TYPE=ODS-MAIN
my_taskid = "SDM_EMPLOYEE_H"
SDM_EMPLOYEE_H = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ",${END_DT_CHAR}"+
        "); End;"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UG_GBD_RFQ_TRACKER_WH"
ODS_UG_GBD_RFQ_TRACKER_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/GBD/UG_GBD_RFQ_TRACKER_{{var.value.EDC}}.D"
    )

# JOB_TYPE=EXE
my_taskid = "ODS_UG_GBD_RFQ_TRACKER_CPD"
ODS_UG_GBD_RFQ_TRACKER_CPD = BashOperator(
    task_id=my_taskid,
    bash_command="cp {{var.value.DIR_SOURCE}}UPD/GBD/UG_GBD_RFQ_TRACKER_{{var.value.EDC}}.D  {{var.value.DIR_TEMP}}/UPD/UG_GBD_RFQ_TRACKER.D"
    )

# JOB_TYPE=ISQL
my_taskid = "UG_GBD_RFQ_TRACKER_STG"
UG_GBD_RFQ_TRACKER_STG = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    sql= "TRUNCATE TABLE STAGE.UG_GBD_RFQ_TRACKER"

    )

# JOB_TYPE=ODS-IMP
my_taskid = "ODS_UG_GBD_RFQ_TRACKER_LD"
ODS_UG_GBD_RFQ_TRACKER_LD = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh {{var.value.ETLUSER}}  {{var.value.ETLPWD}} {{var.value.DW_HOST}} {{var.value.EDC}}"
    )

# JOB_TYPE=SQL
my_taskid = "UG_GBD_RFQ_TRACKER"
UG_GBD_RFQ_TRACKER = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UG_GBD_REVENUE_WH"
ODS_UG_GBD_REVENUE_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/GBD/UG_GBD_REVENUE_{{var.value.EDC}}.D"
    )

# JOB_TYPE=EXE
my_taskid = "ODS_UG_GBD_REVENUE_CPD"
ODS_UG_GBD_REVENUE_CPD = BashOperator(
    task_id=my_taskid,
    bash_command="cp {{var.value.DIR_SOURCE}}UPD/GBD/UG_GBD_REVENUE_{{var.value.EDC}}.D  {{var.value.DIR_TEMP}}/UPD/UG_GBD_REVENUE.D"
    )

# JOB_TYPE=ISQL
my_taskid = "UG_GBD_REVENUE_STG"
UG_GBD_REVENUE_STG = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    sql= "TRUNCATE TABLE STAGE.UG_GBD_REVENUE"

    )

# JOB_TYPE=ODS-IMP
my_taskid = "ODS_UG_GBD_REVENUE_LD"
ODS_UG_GBD_REVENUE_LD = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh {{var.value.ETLUSER}}  {{var.value.ETLPWD}} {{var.value.DW_HOST}} {{var.value.EDC}}"
    )

# JOB_TYPE=SQL
my_taskid = "UG_GBD_REVENUE"
UG_GBD_REVENUE = OracleOperatorWithTemplatedParams(
    task_id=my_taskid,
    parameters=({":END_DT_CHAR":"{{ ds_nodash }}"}),
    sql= "Begin SQLEXT." + my_taskid + "_SP("+  
        ":END_DT_CHAR"+
        "); End;"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Customer_Model_Name_WH"
ODS_UC_Customer_Model_Name_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Customer_Model_Name.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Customer_Model_Name"
ODS_UC_Customer_Model_Name = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Customer_Model_Name|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Customer_PO_Management_WH"
ODS_UC_Customer_PO_Management_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Customer_PO_Management.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Customer_PO_Management"
ODS_UC_Customer_PO_Management = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Customer_PO_Management|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_NC_Customer_Rebate_PN_WH"
ODS_UC_NC_Customer_Rebate_PN_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_NC_Customer_Rebate_PN.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_NC_Customer_Rebate_PN"
ODS_UC_NC_Customer_Rebate_PN = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_NC_Customer_Rebate_PN|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Pre_Project_information_WH"
ODS_UC_Pre_Project_information_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Pre_Project_information.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Pre_Project_information"
ODS_UC_Pre_Project_information = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Pre_Project_information|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Premium_Freight_WH"
ODS_UC_Premium_Freight_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Premium_Freight.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Premium_Freight"
ODS_UC_Premium_Freight = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Premium_Freight|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_RFQ_Critical_Parts_MAP_WH"
ODS_UC_RFQ_Critical_Parts_MAP_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_RFQ_Critical_Parts_MAP.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_RFQ_Critical_Parts_MAP"
ODS_UC_RFQ_Critical_Parts_MAP = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_RFQ_Critical_Parts_MAP|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_RFQ_Freight_Estimate_MAP_WH"
ODS_UC_RFQ_Freight_Estimate_MAP_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_RFQ_Freight_Estimate_MAP.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_RFQ_Freight_Estimate_MAP"
ODS_UC_RFQ_Freight_Estimate_MAP = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_RFQ_Freight_Estimate_MAP|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_RFQ_Quotation_History_MAP_WH"
ODS_UC_RFQ_Quotation_History_MAP_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_RFQ_Quotation_History_MAP.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_RFQ_Quotation_History_MAP"
ODS_UC_RFQ_Quotation_History_MAP = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_RFQ_Quotation_History_MAP|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_NC_ROYALTY_REPORT_WH"
ODS_UC_NC_ROYALTY_REPORT_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_NC_ROYALTY_REPORT.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_NC_ROYALTY_REPORT"
ODS_UC_NC_ROYALTY_REPORT = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_NC_ROYALTY_REPORT|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Tier1_OEM_Mapping_Table_WH"
ODS_UC_Tier1_OEM_Mapping_Table_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Tier1_OEM_Mapping_Table.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Tier1_OEM_Mapping_Table"
ODS_UC_Tier1_OEM_Mapping_Table = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Tier1_OEM_Mapping_Table|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_ASCP_Risk_Shipment_Weekly_WH"
ODS_UC_ASCP_Risk_Shipment_Weekly_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_ASCP_Risk_Shipment_Weekly.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_ASCP_Risk_Shipment_Weekly"
ODS_UC_ASCP_Risk_Shipment_Weekly = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_ASCP_Risk_Shipment_Weekly|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_RFQ_SAS_MAP_WH"
ODS_UC_RFQ_SAS_MAP_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_RFQ_SAS_MAP.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_RFQ_SAS_MAP"
ODS_UC_RFQ_SAS_MAP = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_RFQ_SAS_MAP|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_RFQ_NW_Commodity_Code_WH"
ODS_UC_RFQ_NW_Commodity_Code_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_RFQ_NW_Commodity_Code.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_RFQ_NW_Commodity_Code"
ODS_UC_RFQ_NW_Commodity_Code = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_RFQ_NW_Commodity_Code|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Average_Antenna_of_Notebook_WH"
ODS_UC_Average_Antenna_of_Notebook_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Average_Antenna_of_Notebook.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Average_Antenna_of_Notebook"
ODS_UC_Average_Antenna_of_Notebook = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Average_Antenna_of_Notebook|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UG_SPLIT_RATIO_WH"
ODS_UG_SPLIT_RATIO_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UG_SPLIT_RATIO.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UG_SPLIT_RATIO"
ODS_UG_SPLIT_RATIO = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUG_SPLIT_RATIO|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UG_PIPELINE_PROJECT_CONVERSION_WH"
ODS_UG_PIPELINE_PROJECT_CONVERSION_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UG_PIPELINE_PROJECT_CONVERSION.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UG_PIPELINE_PROJECT_CONVERSION"
ODS_UG_PIPELINE_PROJECT_CONVERSION = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUG_PIPELINE_PROJECT_CONVERSION|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_SENIORITY_WH"
ODS_UH_SENIORITY_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_SENIORITY.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_SENIORITY"
ODS_UH_SENIORITY = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_SENIORITY|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_HEADCOUNT_BUDGET_WH"
ODS_UH_HEADCOUNT_BUDGET_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_HEADCOUNT_BUDGET.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_HEADCOUNT_BUDGET"
ODS_UH_HEADCOUNT_BUDGET = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_HEADCOUNT_BUDGET|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_RDEXPENSE_WH"
ODS_UH_RDEXPENSE_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_RDEXPENSE.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_RDEXPENSE"
ODS_UH_RDEXPENSE = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_RDEXPENSE|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_WORKPLACE_MAPPING_WH"
ODS_UH_WORKPLACE_MAPPING_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_WORKPLACE_MAPPING.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_WORKPLACE_MAPPING"
ODS_UH_WORKPLACE_MAPPING = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_WORKPLACE_MAPPING|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_WORKLOCATION_WH"
ODS_UH_WORKLOCATION_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_WORKLOCATION.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_WORKLOCATION"
ODS_UH_WORKLOCATION = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_WORKLOCATION|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_WORKLOCATION_MAPPING_WH"
ODS_UH_WORKLOCATION_MAPPING_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_WORKLOCATION_MAPPING.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_WORKLOCATION_MAPPING"
ODS_UH_WORKLOCATION_MAPPING = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_WORKLOCATION_MAPPING|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_DEPTABBRE_BU_MAPPING_WH"
ODS_UH_DEPTABBRE_BU_MAPPING_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_DEPTABBRE_BU_MAPPING.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_DEPTABBRE_BU_MAPPING"
ODS_UH_DEPTABBRE_BU_MAPPING = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_DEPTABBRE_BU_MAPPING|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_DEPTABBRE_WH"
ODS_UH_DEPTABBRE_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_DEPTABBRE.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_DEPTABBRE"
ODS_UH_DEPTABBRE = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_DEPTABBRE|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_DEPTUNIT_MAPPING_WH"
ODS_UH_DEPTUNIT_MAPPING_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_DEPTUNIT_MAPPING.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_DEPTUNIT_MAPPING"
ODS_UH_DEPTUNIT_MAPPING = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_DEPTUNIT_MAPPING|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_PERSONNEL_CATEGORY_WH"
ODS_UH_PERSONNEL_CATEGORY_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_PERSONNEL_CATEGORY.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_PERSONNEL_CATEGORY"
ODS_UH_PERSONNEL_CATEGORY = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_PERSONNEL_CATEGORY|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_PERSONNEL_CATEGORY_MAPPING_WH"
ODS_UH_PERSONNEL_CATEGORY_MAPPING_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_PERSONNEL_CATEGORY_MAPPING.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_PERSONNEL_CATEGORY_MAPPING"
ODS_UH_PERSONNEL_CATEGORY_MAPPING = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_PERSONNEL_CATEGORY_MAPPING|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_PERSONNEL_SUBCATE_MAPPING_WH"
ODS_UH_PERSONNEL_SUBCATE_MAPPING_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_PERSONNEL_SUBCATE_MAPPING.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_PERSONNEL_SUBCATE_MAPPING"
ODS_UH_PERSONNEL_SUBCATE_MAPPING = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_PERSONNEL_SUBCATE_MAPPING|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_EMPLOYMENTTYPE_MAPPING_WH"
ODS_UH_EMPLOYMENTTYPE_MAPPING_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_EMPLOYMENTTYPE_MAPPING.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_EMPLOYMENTTYPE_MAPPING"
ODS_UH_EMPLOYMENTTYPE_MAPPING = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_EMPLOYMENTTYPE_MAPPING|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_STAFFSTATUS_WH"
ODS_UH_STAFFSTATUS_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_STAFFSTATUS.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_STAFFSTATUS"
ODS_UH_STAFFSTATUS = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_STAFFSTATUS|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UH_STAFFSTATUS_TOBE_ONBOARD_WH"
ODS_UH_STAFFSTATUS_TOBE_ONBOARD_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UH_STAFFSTATUS_TOBE_ONBOARD.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UH_STAFFSTATUS_TOBE_ONBOARD"
ODS_UH_STAFFSTATUS_TOBE_ONBOARD = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUH_STAFFSTATUS_TOBE_ONBOARD|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UM_RiskShipmentUpload_WH"
ODS_UM_RiskShipmentUpload_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UM_RiskShipmentUpload.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UM_RiskShipmentUpload"
ODS_UM_RiskShipmentUpload = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUM_RiskShipmentUpload|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UM_SMT_TIME_WH"
ODS_UM_SMT_TIME_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UM_SMT_TIME.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UM_SMT_TIME"
ODS_UM_SMT_TIME = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUM_SMT_TIME|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UM_SMT_WH"
ODS_UM_SMT_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UM_SMT.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UM_SMT"
ODS_UM_SMT = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUM_SMT|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UM_ForecastUploadModel_WH"
ODS_UM_ForecastUploadModel_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UM_ForecastUploadModel.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UM_ForecastUploadModel"
ODS_UM_ForecastUploadModel = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUM_ForecastUploadModel|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UM_Shift_WH"
ODS_UM_Shift_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UM_Shift.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UM_Shift"
ODS_UM_Shift = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUM_Shift|(空白)"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UM_Resource_Mapping_Process"
ODS_UM_Resource_Mapping_Process = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUM_Resource_Mapping_Process|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UM_Resource_Mapping_Process_WH"
ODS_UM_Resource_Mapping_Process_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UM_Resource_Mapping_Process.D"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UM_Work_in_Process_Category_WH"
ODS_UM_Work_in_Process_Category_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UM_Work_in_Process_Category.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UM_Work_in_Process_Category"
ODS_UM_Work_in_Process_Category = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUM_Work_in_Process_Category|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UP_consign_vendor_product_map_WH"
ODS_UP_consign_vendor_product_map_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UP_consign_vendor_product_map.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UP_consign_vendor_product_map"
ODS_UP_consign_vendor_product_map = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUP_consign_vendor_product_map|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UP_Expense_Budget_product_map_WH"
ODS_UP_Expense_Budget_product_map_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UP_Expense_Budget_product_map.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UP_Expense_Budget_product_map"
ODS_UP_Expense_Budget_product_map = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUP_Expense_Budget_product_map|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_MtlScrapCost_WH"
ODS_UQ_MtlScrapCost_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_MtlScrapCost.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_MtlScrapCost"
ODS_UQ_MtlScrapCost = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_MtlScrapCost|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_CSDCustomerPaidService_WH"
ODS_UQ_CSDCustomerPaidService_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_CSDCustomerPaidService.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_CSDCustomerPaidService"
ODS_UQ_CSDCustomerPaidService = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_CSDCustomerPaidService|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_CSDPlannedShippingQty_WH"
ODS_UQ_CSDPlannedShippingQty_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_CSDPlannedShippingQty.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_CSDPlannedShippingQty"
ODS_UQ_CSDPlannedShippingQty = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_CSDPlannedShippingQty|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_InventoryOwner_WH"
ODS_UQ_InventoryOwner_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_InventoryOwner.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_InventoryOwner"
ODS_UQ_InventoryOwner = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_InventoryOwner|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_OnSiteReworkQty_WH"
ODS_UQ_OnSiteReworkQty_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_OnSiteReworkQty.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_OnSiteReworkQty"
ODS_UQ_OnSiteReworkQty = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_OnSiteReworkQty|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_QualityReturnQty_WH"
ODS_UQ_QualityReturnQty_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_QualityReturnQty.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_QualityReturnQty"
ODS_UQ_QualityReturnQty = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_QualityReturnQty|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_JQMList_WH"
ODS_UQ_JQMList_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_JQMList.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_JQMList"
ODS_UQ_JQMList = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_JQMList|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_IQC_DailyManpower_S1_WH"
ODS_UQ_IQC_DailyManpower_S1_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_IQC_DailyManpower_S1.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_IQC_DailyManpower_S1"
ODS_UQ_IQC_DailyManpower_S1 = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_IQC_DailyManpower_S1|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_IQC_DailyManpower_NQJ_WH"
ODS_UQ_IQC_DailyManpower_NQJ_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_IQC_DailyManpower_NQJ.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_IQC_DailyManpower_NQJ"
ODS_UQ_IQC_DailyManpower_NQJ = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_IQC_DailyManpower_NQJ|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_IQC_DailyManpower_NYC_WH"
ODS_UQ_IQC_DailyManpower_NYC_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_IQC_DailyManpower_NYC.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_IQC_DailyManpower_NYC"
ODS_UQ_IQC_DailyManpower_NYC = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_IQC_DailyManpower_NYC|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_IQC_DailyManpower_NQX_WH"
ODS_UQ_IQC_DailyManpower_NQX_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_IQC_DailyManpower_NQX.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_IQC_DailyManpower_NQX"
ODS_UQ_IQC_DailyManpower_NQX = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_IQC_DailyManpower_NQX|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_IQC_DailyManpower_NVN_WH"
ODS_UQ_IQC_DailyManpower_NVN_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_IQC_DailyManpower_NVN.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_IQC_DailyManpower_NVN"
ODS_UQ_IQC_DailyManpower_NVN = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_IQC_DailyManpower_NVN|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_IQC_DailyManpower_S2_WH"
ODS_UQ_IQC_DailyManpower_S2_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_IQC_DailyManpower_S2.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_IQC_DailyManpower_S2"
ODS_UQ_IQC_DailyManpower_S2 = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_IQC_DailyManpower_S2|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_InventoryOwnerList_WH"
ODS_UQ_InventoryOwnerList_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_InventoryOwnerList.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_InventoryOwnerList"
ODS_UQ_InventoryOwnerList = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_InventoryOwnerList|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_MoPartType_WH"
ODS_UQ_MoPartType_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_MoPartType.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_MoPartType"
ODS_UQ_MoPartType = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_MoPartType|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_Escape_WH"
ODS_UQ_Escape_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_Escape.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_Escape"
ODS_UQ_Escape = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_Escape|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_US_reason_code_WH"
ODS_US_reason_code_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/US_reason_code.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_US_reason_code"
ODS_US_reason_code = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUS_reason_code|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_FaultInjectionRecord_WH"
ODS_UQ_FaultInjectionRecord_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_FaultInjectionRecord.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_FaultInjectionRecord"
ODS_UQ_FaultInjectionRecord = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_FaultInjectionRecord|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_QSCANTrackingRecord_WH"
ODS_UQ_QSCANTrackingRecord_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_QSCANTrackingRecord.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_QSCANTrackingRecord"
ODS_UQ_QSCANTrackingRecord = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_QSCANTrackingRecord|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UQ_ModelMPInfo_WH"
ODS_UQ_ModelMPInfo_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UQ_ModelMPInfo.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UQ_ModelMPInfo"
ODS_UQ_ModelMPInfo = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUQ_ModelMPInfo|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Customer_Grouping_Map_WH"
ODS_UC_Customer_Grouping_Map_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Customer_Grouping_Map.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Customer_Grouping_Map"
ODS_UC_Customer_Grouping_Map = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Customer_Grouping_Map|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_GROUP_CUSTOMER_INDUSTRY_TYPE_WH"
ODS_UC_GROUP_CUSTOMER_INDUSTRY_TYPE_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_GROUP_CUSTOMER_INDUSTRY_TYPE.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_GROUP_CUSTOMER_INDUSTRY_TYPE"
ODS_UC_GROUP_CUSTOMER_INDUSTRY_TYPE = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_GROUP_CUSTOMER_INDUSTRY_TYPE|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Market_Share_Market_Shipment_WH"
ODS_UC_Market_Share_Market_Shipment_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Market_Share_Market_Shipment.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Market_Share_Market_Shipment"
ODS_UC_Market_Share_Market_Shipment = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Market_Share_Market_Shipment|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Market_Share_WNC_Shipment_WH"
ODS_UC_Market_Share_WNC_Shipment_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Market_Share_WNC_Shipment.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Market_Share_WNC_Shipment"
ODS_UC_Market_Share_WNC_Shipment = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Market_Share_WNC_Shipment|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Model_product_map_WH"
ODS_UC_Model_product_map_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Model_product_map.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Model_product_map"
ODS_UC_Model_product_map = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Model_product_map|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_Product_Mapping_Table_WH"
ODS_UC_Product_Mapping_Table_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_Product_Mapping_Table.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_Product_Mapping_Table"
ODS_UC_Product_Mapping_Table = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_Product_Mapping_Table|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_WNC_BI_SHIPMENT_QTY_TABLE_WH"
ODS_UC_WNC_BI_SHIPMENT_QTY_TABLE_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_WNC_BI_SHIPMENT_QTY_TABLE.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_WNC_BI_SHIPMENT_QTY_TABLE"
ODS_UC_WNC_BI_SHIPMENT_QTY_TABLE = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_WNC_BI_SHIPMENT_QTY_TABLE|(空白)"
    )

# JOB_TYPE=WATCH
my_taskid = "ODS_UC_SW_Centric_Product_Model_WH"
ODS_UC_SW_Centric_Product_Model_WH = FileSensor(
    task_id=my_taskid,
    filepath= "{{ var.value.DIR_SOURCE }}UPD/UC_SW_Centric_Product_Model.D"
    )

# JOB_TYPE=ODS-UIMP
my_taskid = "ODS_UC_SW_Centric_Product_Model"
ODS_UC_SW_Centric_Product_Model = BashOperator(
    task_id=my_taskid,
    bash_command="{{var.value.DIR_BIN}}ods_ora_imp.sh UPDUC_SW_Centric_Product_Model|(空白)"
    )
