



# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/11/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
# import sqlg_jobs 
import sqlg_jobs_MFG


#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams

def f_SYS_STS_STG():
    logging.info('Control flow: STAGE status ')

args = {
    'owner': 'airflow',
    'start_date': airflow.utils.dates.days_ago(1),
    'provide_context': True
}

tmpl_search_path = Variable.get("sql_path")

my_taskid = 'SYS_STS_STG'
D_STG_INIT = airflow.DAG(
    'D_STG_INIT',
    schedule_interval=timedelta(1),
    default_args=args,
    template_searchpath=tmpl_search_path,    
    max_active_runs=1)

SYS_STS_STG = PythonOperator(task_id=my_taskid,
                    python_callable=f_SYS_STS_STG,
                    provide_context=False,
                    dag=D_STG_INIT)

my_taskid = 'D_STG_INITxSYS_STS_STG'                    
D_STG_INITxSYS_STS_STG = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_STG_INIT',
    external_task_id='SYS_STS_STG',
    execution_delta=None,  # Same day as today
    )

# Flow dag    
# DB_NAME = 'DWH'    
D_ODS_MFG = airflow.DAG(    "D_ODS_MFG",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_MFG"
D_STG_INITxSYS_STS_STGxD_ODS_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_MFG"
D_STG_INITxSYS_STS_STGxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_SDM_MFGxSDM_FPYR_IN_SINGLE_STATIONxD_SDM_MFG
### D_SDM_MFGxSDM_AUTO_EQUIPMENT_STDHxD_SDM_MFG
### D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG

my_taskid = "D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG"
D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_MFG",
    external_task_id="XXWIP_STOREIN_USAGE_TEMP",
    execution_delta=None,  # Same day as today
)
### D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG

my_taskid = "D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG"
D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_SDM_SCM",
    external_task_id="SDM_ORG_HIER",
    execution_delta=None,  # Same day as today
)
### D_SDM_MFGxSDM_STANDARD_HOURxD_SDM_MFG
### D_SDM_MFGxSDM_SFCS_OUTPUT_QTYxD_SDM_MFG
### D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG

my_taskid = "D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG"
D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="COPQ_FCTACTUALCOST",
    execution_delta=None,  # Same day as today
)
### D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG

my_taskid = "D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG"
D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="COPQ_DIMCATEGORY",
    execution_delta=None,  # Same day as today
)
### D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG

my_taskid = "D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG"
D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="BI_DIMMULTIORG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_MFG"
D_STG_INITxSYS_STS_STGxD_DM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs_MFG.WO_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.WO_WS1)

sqlg_jobs_MFG.SPN_TABL_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.SPN_TABL_WS1)

sqlg_jobs_MFG.STAGE_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.STAGE_WS1)

sqlg_jobs_MFG.WO_ROUTING_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.WO_ROUTING_WS1)

sqlg_jobs_MFG.YIELDRATEWO_YR_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.YIELDRATEWO_YR_WS1)

sqlg_jobs_MFG.SMT_LINE_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.SMT_LINE_WS1)

sqlg_jobs_MFG.ABNORMAL_DETAIL_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.ABNORMAL_DETAIL_WS1)

sqlg_jobs_MFG.PD_ABNORMALCODE_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.PD_ABNORMALCODE_WS1)

sqlg_jobs_MFG.MO_STATUS_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.MO_STATUS_WS1)

sqlg_jobs_MFG.MO_OUTPUT_QTY_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.MO_OUTPUT_QTY_WS1)

sqlg_jobs_MFG.CHANGE_LINE_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.CHANGE_LINE_WS1)

sqlg_jobs_MFG.TRIAL_FORMULA_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.TRIAL_FORMULA_WS1)

sqlg_jobs_MFG.TRIAL_FORMULA_SMT_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.TRIAL_FORMULA_SMT_WS1)

sqlg_jobs_MFG.ASS_RESULT_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.ASS_RESULT_WS1)

sqlg_jobs_MFG.ASS_STAGE_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.ASS_STAGE_WS1)

sqlg_jobs_MFG.BU_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.BU_WS1)

sqlg_jobs_MFG.BI_DIMBUDESC.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.BI_DIMBUDESC)

sqlg_jobs_MFG.XXWIP_STOREIN_USAGE_TEMP.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.XXWIP_STOREIN_USAGE_TEMP)

sqlg_jobs_MFG.MV_XX_MTL_ITEM_CATEGORY.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.MV_XX_MTL_ITEM_CATEGORY)

sqlg_jobs_MFG.WIP_ENTITIES.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.WIP_ENTITIES)

sqlg_jobs_MFG.WIP_LINES.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.WIP_LINES)

sqlg_jobs_MFG.WIP_DISCRETE_JOBS.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.WIP_DISCRETE_JOBS)

sqlg_jobs_MFG.LINE_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_WS1)

sqlg_jobs_MFG.LINE_NQJ.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_NQJ)

sqlg_jobs_MFG.LINE_NQX.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_NQX)

sqlg_jobs_MFG.LINE_VN1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_VN1)

sqlg_jobs_MFG.LINE_WS2.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_WS2)

sqlg_jobs_MFG.LINE_LIST_NQJ.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_LIST_NQJ)

sqlg_jobs_MFG.LINE_LIST_VN1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_LIST_VN1)

sqlg_jobs_MFG.LINE_LIST_WS1.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_LIST_WS1)

sqlg_jobs_MFG.LINE_LIST_WS2.dag=D_ODS_MFG
D_STG_INITxSYS_STS_STGxD_ODS_MFG.set_downstream(sqlg_jobs_MFG.LINE_LIST_WS2)

D_SDM_MFG = airflow.DAG(    "D_SDM_MFG",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_MFG"
D_STG_INITxSYS_STS_STGxD_ODS_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_MFG"
D_STG_INITxSYS_STS_STGxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_SDM_MFGxSDM_FPYR_IN_SINGLE_STATIONxD_SDM_MFG
### D_SDM_MFGxSDM_AUTO_EQUIPMENT_STDHxD_SDM_MFG
### D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG

my_taskid = "D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG"
D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_MFG",
    external_task_id="XXWIP_STOREIN_USAGE_TEMP",
    execution_delta=None,  # Same day as today
)
### D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG

my_taskid = "D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG"
D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_SDM_SCM",
    external_task_id="SDM_ORG_HIER",
    execution_delta=None,  # Same day as today
)
### D_SDM_MFGxSDM_STANDARD_HOURxD_SDM_MFG
### D_SDM_MFGxSDM_SFCS_OUTPUT_QTYxD_SDM_MFG
### D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG

my_taskid = "D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG"
D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="COPQ_FCTACTUALCOST",
    execution_delta=None,  # Same day as today
)
### D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG

my_taskid = "D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG"
D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="COPQ_DIMCATEGORY",
    execution_delta=None,  # Same day as today
)
### D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG

my_taskid = "D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG"
D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="BI_DIMMULTIORG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_MFG"
D_STG_INITxSYS_STS_STGxD_DM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs_MFG.SDM_MANUFACTURING_ORDER.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_MANUFACTURING_ORDER)

sqlg_jobs_MFG.SDM_FPYR_IN_SINGLE_STATION.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_FPYR_IN_SINGLE_STATION)

sqlg_jobs_MFG.SDM_FIRST_PASS_YIELD_RATE.dag=D_SDM_MFG
sqlg_jobs_MFG.SDM_FPYR_IN_SINGLE_STATION.set_downstream(sqlg_jobs_MFG.SDM_FIRST_PASS_YIELD_RATE)

sqlg_jobs_MFG.SDM_STAGE.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_STAGE)

sqlg_jobs_MFG.SDM_PROCESS.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_PROCESS)

sqlg_jobs_MFG.SDM_SFCS_LINE.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_SFCS_LINE)

sqlg_jobs_MFG.SDM_PRODUCTIVITY_LINE.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_PRODUCTIVITY_LINE)

sqlg_jobs_MFG.SDM_SHIFT.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_SHIFT)

sqlg_jobs_MFG.SDM_AUTO_EQUIPMENT_STDH.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_AUTO_EQUIPMENT_STDH)

sqlg_jobs_MFG.SDM_ACTIVATION.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_ACTIVATION)
sqlg_jobs_MFG.SDM_AUTO_EQUIPMENT_STDH.set_downstream(sqlg_jobs_MFG.SDM_ACTIVATION)

sqlg_jobs_MFG.SDM_SFCS_OUTPUT_QTY.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_SFCS_OUTPUT_QTY)

sqlg_jobs_MFG.SDM_STANDARD_HOUR.dag=D_SDM_MFG
D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_STANDARD_HOUR)
D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_STANDARD_HOUR)
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_STANDARD_HOUR)

sqlg_jobs_MFG.SDM_DIPATP_SFCS_OUTPUT_HOUR.dag=D_SDM_MFG
sqlg_jobs_MFG.SDM_STANDARD_HOUR.set_downstream(sqlg_jobs_MFG.SDM_DIPATP_SFCS_OUTPUT_HOUR)
sqlg_jobs_MFG.SDM_SFCS_OUTPUT_QTY.set_downstream(sqlg_jobs_MFG.SDM_DIPATP_SFCS_OUTPUT_HOUR)

sqlg_jobs_MFG.SDM_DIPATP_TTL_INPUT_HOURS.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_DIPATP_TTL_INPUT_HOURS)

sqlg_jobs_MFG.SDM_PRODUCTIVITY_DIPATP.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_PRODUCTIVITY_DIPATP)

sqlg_jobs_MFG.SDM_SMT_SFCS_OUTPUT_HOUR.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_SMT_SFCS_OUTPUT_HOUR)

sqlg_jobs_MFG.SDM_SMT_WORK_HOUR.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_SMT_WORK_HOUR)

sqlg_jobs_MFG.SDM_PRODUCTIVITY_SMT.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_PRODUCTIVITY_SMT)

sqlg_jobs_MFG.SDM_ORACLE_OUTPUT_HOUR.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_ORACLE_OUTPUT_HOUR)

sqlg_jobs_MFG.SDM_COST_OF_POOR_QLY.dag=D_SDM_MFG
D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_COST_OF_POOR_QLY)
D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_COST_OF_POOR_QLY)
D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_COST_OF_POOR_QLY)
D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_COST_OF_POOR_QLY)

sqlg_jobs_MFG.SDM_COST_OF_POOR_QUALITY_PC.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_COST_OF_POOR_QUALITY_PC)

sqlg_jobs_MFG.SDM_SCRAP_AMT.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_SCRAP_AMT)

sqlg_jobs_MFG.SDM_SCRAP_AMT_RATIO.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_SCRAP_AMT_RATIO)

sqlg_jobs_MFG.SDM_FCST_DEMAND_QTY_LMEV.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_FCST_DEMAND_QTY_LMEV)

sqlg_jobs_MFG.FCST_DEMAND_AMT_LMEV.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.FCST_DEMAND_AMT_LMEV)

sqlg_jobs_MFG.SDM_EST_DLV_IN_CURRENT_MONTH.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_EST_DLV_IN_CURRENT_MONTH)

sqlg_jobs_MFG.SDM_EST_DLV_AMT_HIT_RATE.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_EST_DLV_AMT_HIT_RATE)

sqlg_jobs_MFG.SDM_ACM_SHIPMENT_AMT_HIT_RATE.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_ACM_SHIPMENT_AMT_HIT_RATE)

sqlg_jobs_MFG.SDM_PRD_OTPT_HIT_R_QTY_LMEV.dag=D_SDM_MFG
D_STG_INITxSYS_STS_STGxD_SDM_MFG.set_downstream(sqlg_jobs_MFG.SDM_PRD_OTPT_HIT_R_QTY_LMEV)

D_DM_MFG = airflow.DAG(    "D_DM_MFG",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1)

### D_STG_INITxSYS_STS_STGxD_ODS_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_MFG"
D_STG_INITxSYS_STS_STGxD_ODS_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_SDM_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_SDM_MFG"
D_STG_INITxSYS_STS_STGxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
### D_SDM_MFGxSDM_FPYR_IN_SINGLE_STATIONxD_SDM_MFG
### D_SDM_MFGxSDM_AUTO_EQUIPMENT_STDHxD_SDM_MFG
### D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG

my_taskid = "D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG"
D_ODS_MFGxXXWIP_STOREIN_USAGE_TEMPxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_MFG",
    external_task_id="XXWIP_STOREIN_USAGE_TEMP",
    execution_delta=None,  # Same day as today
)
### D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG

my_taskid = "D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG"
D_SDM_SCMxSDM_ORG_HIERxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_SDM_SCM",
    external_task_id="SDM_ORG_HIER",
    execution_delta=None,  # Same day as today
)
### D_SDM_MFGxSDM_STANDARD_HOURxD_SDM_MFG
### D_SDM_MFGxSDM_SFCS_OUTPUT_QTYxD_SDM_MFG
### D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG

my_taskid = "D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG"
D_ODS_QAMxCOPQ_FCTACTUALCOSTxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="COPQ_FCTACTUALCOST",
    execution_delta=None,  # Same day as today
)
### D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG

my_taskid = "D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG"
D_ODS_QAMxCOPQ_DIMCATEGORYxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="COPQ_DIMCATEGORY",
    execution_delta=None,  # Same day as today
)
### D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG

my_taskid = "D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG"
D_ODS_QAMxBI_DIMMULTIORGxD_SDM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_ODS_QAM",
    external_task_id="BI_DIMMULTIORG",
    execution_delta=None,  # Same day as today
)
### D_STG_INITxSYS_STS_STGxD_DM_MFG

my_taskid = "D_STG_INITxSYS_STS_STGxD_DM_MFG"
D_STG_INITxSYS_STS_STGxD_DM_MFG= ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    execution_delta=None,  # Same day as today
)
sqlg_jobs_MFG.DIM_MANUFACTURING_ORDER.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.DIM_MANUFACTURING_ORDER)

sqlg_jobs_MFG.DIM_STAGE.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.DIM_STAGE)

sqlg_jobs_MFG.DIM_PROCESS.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.DIM_PROCESS)

sqlg_jobs_MFG.DIM_SFCS_LINE.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.DIM_SFCS_LINE)

sqlg_jobs_MFG.DIM_PRODUCTIVITY_LINE.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.DIM_PRODUCTIVITY_LINE)

sqlg_jobs_MFG.DIM_SHIFT.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.DIM_SHIFT)

sqlg_jobs_MFG.FCT_FPYR_IN_SINGLE_STATION.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.FCT_FPYR_IN_SINGLE_STATION)

sqlg_jobs_MFG.FCT_FIRST_PASS_YIELD_RATE.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.FCT_FIRST_PASS_YIELD_RATE)

sqlg_jobs_MFG.FCT_PRD_OTPT_HIT_R_QTY_LMEV.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.FCT_PRD_OTPT_HIT_R_QTY_LMEV)

sqlg_jobs_MFG.FCT_ACM_SHIPMENT_AMT_HIT_RATE.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.FCT_ACM_SHIPMENT_AMT_HIT_RATE)

sqlg_jobs_MFG.FCT_MFG_EST_DLV_AMT_HIT_RATE.dag=D_DM_MFG
D_STG_INITxSYS_STS_STGxD_DM_MFG.set_downstream(sqlg_jobs_MFG.FCT_MFG_EST_DLV_AMT_HIT_RATE)

