
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/11/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams
import sqlg_jobs_PRD


args = {
    "owner": "JESSEWEI",
    'start_date': airflow.utils.dates.days_ago(1),
    'provide_context': True
}

ExternalTaskSensor.ui_color = 'white'
ExternalTaskSensor.ui_fgcolor = 'blue'

tmpl_search_path = Variable.get("sql_path")

# Flow dag    
# DB_NAME = 'DWH' 
D_ODS_PRD = airflow.DAG(
    "D_ODS_PRD",
    tags=["PRD"],
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)


my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_PRD"
D_STG_INITxSYS_STS_STGxD_ODS_PRD= ExternalTaskSensor(
#    schedule_interval=None,
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
#    dag=D_ODS_PRD,
#    execution_delta=None,  # Same day as today
)
sqlg_jobs_PRD.FND_COLUMNS.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs_PRD.FND_COLUMNS)

sqlg_jobs_PRD.FND_COLUMNS_H.dag=D_ODS_PRD
sqlg_jobs_PRD.FND_COLUMNS.set_downstream(sqlg_jobs_PRD.FND_COLUMNS_H)

sqlg_jobs_PRD.FND_LOOKUP_TYPES.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs_PRD.FND_LOOKUP_TYPES)

sqlg_jobs_PRD.PCS_LINEER.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs_PRD.PCS_LINEER)

sqlg_jobs_PRD.BTMS_EXPENSEPROJECT.dag=D_ODS_PRD
D_STG_INITxSYS_STS_STGxD_ODS_PRD.set_downstream(sqlg_jobs_PRD.BTMS_EXPENSEPROJECT)

