
CALL SQLEXT.SP_DROP_IF_EXISTS ('DM', 'FCT_TESTING_EXPENSE');
CREATE TABLE DM.FCT_TESTING_EXPENSE (
       BUSINESS_GROUP                          VARCHAR2(30) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(30) NOT NULL
      ,MODEL                                   VARCHAR2(30) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,TESTING_EXPENSE                         VARCHAR2(30)
      ,CERTIFICATION_EXPENSE                   VARCHAR2(30)
      ,EQT_EXPENSE                             VARCHAR2(30)
      ,EPR_MFG_SAMPLE_BUILD_EXP                VARCHAR2(30)
      ,DATA_DATE                               VARCHAR2(8)
      ,TBL_UPD_TIME                            DATE
      ,TBL_UPD_SRC                             VARCHAR2(100)
);

ALTER TABLE DM.FCT_TESTING_EXPENSE nologging;

--PK Create Script
ALTER TABLE DM.FCT_TESTING_EXPENSE ADD CONSTRAINT FCT_TESTING_EXPENSE_X PRIMARY KEY(BUSINESS_GROUP,PROJECT_CODE,MODEL,MANUFACTURING_PLANT) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE DM.FCT_TESTING_EXPENSE IS '測試費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.BUSINESS_GROUP IS '標準-事業群';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.PROJECT_CODE IS '專案代碼';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.MODEL IS 'Model';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.MANUFACTURING_PLANT IS '標準-製造廠';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.TESTING_EXPENSE IS '測試費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.CERTIFICATION_EXPENSE IS '認證費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.EQT_EXPENSE IS 'EQT 測試費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.EPR_MFG_SAMPLE_BUILD_EXP IS 'EPR製造樣品費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.DATA_DATE IS 'DataDate';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.TBL_UPD_TIME IS 'Updated Time';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE.TBL_UPD_SRC IS 'Updated Source';

CALL SQLEXT.SP_DROP_IF_EXISTS ('DM', 'FCT_TESTING_EXPENSE_TPX');
CREATE TABLE DM.FCT_TESTING_EXPENSE_TPX AS SELECT * FROM SQLEXT.EXCEPTIONS WHERE 1=2
;




CALL SQLEXT.SP_DROP_IF_EXISTS ('DM', 'FCT_TESTING_EXPENSE_TP1');
CREATE TABLE DM.FCT_TESTING_EXPENSE_TP1 (
       BUSINESS_GROUP                          VARCHAR2(30) NOT NULL
      ,PROJECT_CODE                            VARCHAR2(30) NOT NULL
      ,MODEL                                   VARCHAR2(30) NOT NULL
      ,MANUFACTURING_PLANT                     VARCHAR2(30) NOT NULL
      ,TESTING_EXPENSE                         VARCHAR2(30)
      ,CERTIFICATION_EXPENSE                   VARCHAR2(30)
      ,EQT_EXPENSE                             VARCHAR2(30)
      ,EPR_MFG_SAMPLE_BUILD_EXP                VARCHAR2(30)
);

ALTER TABLE DM.FCT_TESTING_EXPENSE_TP1 nologging;

--PK Create Script
ALTER TABLE DM.FCT_TESTING_EXPENSE_TP1 ADD CONSTRAINT FCT_TESTING_EXPENSE_TP1_X PRIMARY KEY(BUSINESS_GROUP,PROJECT_CODE,MODEL,MANUFACTURING_PLANT) INITIALLY IMMEDIATE;

--Comments Create Script 
COMMENT ON TABLE DM.FCT_TESTING_EXPENSE_TP1 IS '測試費用暫存檔';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.BUSINESS_GROUP IS '標準-事業群';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.PROJECT_CODE IS '專案代碼';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.MODEL IS 'Model';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.MANUFACTURING_PLANT IS '標準-製造廠';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.TESTING_EXPENSE IS '測試費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.CERTIFICATION_EXPENSE IS '認證費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.EQT_EXPENSE IS 'EQT 測試費用';
COMMENT ON COLUMN DM.FCT_TESTING_EXPENSE_TP1.EPR_MFG_SAMPLE_BUILD_EXP IS 'EPR製造樣品費用';



