
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/11/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams
import sqlg_jobs_SCM


args = {
    "owner": "JESSEWEI",
    'start_date': airflow.utils.dates.days_ago(1),
    'provide_context': True
}

ExternalTaskSensor.ui_color = 'white'
ExternalTaskSensor.ui_fgcolor = 'blue'

tmpl_search_path = Variable.get("sql_path")

# Flow dag    
# DB_NAME = 'DWH' 
D_ODS_SCM = airflow.DAG(
    "D_ODS_SCM",
    tags=["SCM"],
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)


my_taskid = "D_STG_INITxSYS_STS_STGxD_ODS_SCM"
D_STG_INITxSYS_STS_STGxD_ODS_SCM= ExternalTaskSensor(
#    schedule_interval=None,
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
#    dag=D_ODS_SCM,
#    execution_delta=None,  # Same day as today
)
sqlg_jobs_SCM.BRAND_CATEGORY.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BRAND_CATEGORY)

sqlg_jobs_SCM.BRAND_DETAIL_SCORE_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BRAND_DETAIL_SCORE_V)

sqlg_jobs_SCM.PLM_BRAND_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PLM_BRAND_V)

sqlg_jobs_SCM.VPE_RANKING_VALUE.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.VPE_RANKING_VALUE)

sqlg_jobs_SCM.UG_RFQ.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.UG_RFQ)

sqlg_jobs_SCM.MTL_CATEGORY_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_CATEGORY_B)

sqlg_jobs_SCM.MTL_CROSS_REFERENCES_VL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_CROSS_REFERENCES_VL)

sqlg_jobs_SCM.MV_ORG_ORG_DEF.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MV_ORG_ORG_DEF)

sqlg_jobs_SCM.PO_HEADERS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_HEADERS_ALL)

sqlg_jobs_SCM.PO_LINES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_LINES_ALL)

sqlg_jobs_SCM.AP_SUPPLIERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.AP_SUPPLIERS)

sqlg_jobs_SCM.AP_SUPPLIER_SITES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.AP_SUPPLIER_SITES_ALL)

sqlg_jobs_SCM.CST_COST_TYPES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.CST_COST_TYPES)

sqlg_jobs_SCM.CST_ITEM_COSTS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.CST_ITEM_COSTS)

sqlg_jobs_SCM.MTL_SECONDARY_INVENTORIES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_SECONDARY_INVENTORIES)

sqlg_jobs_SCM.RCV_TRANSACTIONS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.RCV_TRANSACTIONS)

sqlg_jobs_SCM.BOM_COMPONENTS_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BOM_COMPONENTS_B)

sqlg_jobs_SCM.BOM_STRUCTURES_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.BOM_STRUCTURES_B)

sqlg_jobs_SCM.MTL_ONHAND_QUANTITIES_DETAIL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_ONHAND_QUANTITIES_DETAIL)

sqlg_jobs_SCM.MTL_PARAMETERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_PARAMETERS)

sqlg_jobs_SCM.MTL_TRANSACTION_REASONS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_TRANSACTION_REASONS)

sqlg_jobs_SCM.MTL_TRANSACTION_TYPES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_TRANSACTION_TYPES)

sqlg_jobs_SCM.MV_MTL_CATEGORIES_B_KFV.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MV_MTL_CATEGORIES_B_KFV)

sqlg_jobs_SCM.MV_MTL_ITEM_LOCATIONS_KFV.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MV_MTL_ITEM_LOCATIONS_KFV)

sqlg_jobs_SCM.UI_INV_ADS_SUMMARY_V.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.UI_INV_ADS_SUMMARY_V)

sqlg_jobs_SCM.ERFQ_ITEMVENDOR.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.ERFQ_ITEMVENDOR)

sqlg_jobs_SCM.ERFQ_PRICEDATA_OBC.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.ERFQ_PRICEDATA_OBC)

sqlg_jobs_SCM.SCM_RISK_SHIPMENT_UPLOAD.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.SCM_RISK_SHIPMENT_UPLOAD)

sqlg_jobs_SCM.XXPO_HUB_INVENTORY_TEMP.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.XXPO_HUB_INVENTORY_TEMP)

sqlg_jobs_SCM.VPE_BRAND_SCORE_FINAL_ADJ.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.VPE_BRAND_SCORE_FINAL_ADJ)

sqlg_jobs_SCM.NSP_PO_LINES.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.NSP_PO_LINES)

sqlg_jobs_SCM.NSP_PO_HEADERS.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.NSP_PO_HEADERS)

sqlg_jobs_SCM.RVL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.RVL)

sqlg_jobs_SCM.PO_LINE_LOCATIONS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_LINE_LOCATIONS_ALL)

sqlg_jobs_SCM.PO_REQUISITION_LINES_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_REQUISITION_LINES_ALL)

sqlg_jobs_SCM.PO_REQ_DISTRIBUTIONS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_REQ_DISTRIBUTIONS_ALL)

sqlg_jobs_SCM.XXPO_STR_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.XXPO_STR_ALL)

sqlg_jobs_SCM.SCM_INV_AGE_CUST_ACT_CODE.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.SCM_INV_AGE_CUST_ACT_CODE)

sqlg_jobs_SCM.SCM_INV_AGE_CUST_DETAIL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.SCM_INV_AGE_CUST_DETAIL)

sqlg_jobs_SCM.SCM_INV_AGE_CUST_REPLY.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.SCM_INV_AGE_CUST_REPLY)

sqlg_jobs_SCM.SCM_INV_AGE_CUST_WH.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.SCM_INV_AGE_CUST_WH)

sqlg_jobs_SCM.XXSCR_DOWNSIZING_CANCEL_TEMP.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.XXSCR_DOWNSIZING_CANCEL_TEMP)

sqlg_jobs_SCM.PO_DISTRIBUTIONS_ALL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.PO_DISTRIBUTIONS_ALL)

sqlg_jobs_SCM.SCM_INV_AGE_OBS_DETAIL.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.SCM_INV_AGE_OBS_DETAIL)

sqlg_jobs_SCM.MTL_CROSS_REFERENCES_B.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MTL_CROSS_REFERENCES_B)

sqlg_jobs_SCM.MV_PER_PEOPLE_F.dag=D_ODS_SCM
D_STG_INITxSYS_STS_STGxD_ODS_SCM.set_downstream(sqlg_jobs_SCM.MV_PER_PEOPLE_F)

