
ALTER TABLE SDM.SDM_UPLOAD_CDOC_COUNT_TP1 DISABLE CONSTRAINT SDM_UPLOAD_CDOC_COUNT_TP1_X;
TRUNCATE TABLE SDM.SDM_UPLOAD_CDOC_COUNT_TP1;

INSERT /*+ append */ INTO SDM.SDM_UPLOAD_CDOC_COUNT_TP1 (
      PROJECT_CODE                            
      ,BUSINESS_GROUP                          
      ,MODEL                                   
      ,MANUFACTURING_PLANT                     
      ,DOC_CODE                                
      ,STAGE                                   
      ,UPLOAD_CDOC_COUNT                       
)
WITH SDM_UPLOAD_CDOC_COUNT_V11 AS (
      SELECT
       MA.IDA2A2                          AS IDA2A2
      ,MA.S2BU                            AS S2BU
      ,MA.S2SUBBU                         AS S2SUBBU
      ,replace(MA.S2DEVELOPMENTTYPE,' ','')      AS S2DEVELOPMENTTYPE
      ,MA.S2CURRENTSTAGE                  AS S2CURRENTSTAGE
      ,MA.S2NEXTSTAGE                     AS S2NEXTSTAGE
      ,MA.PROJECT_DEVELOPMENT_FLOW        AS PROJECT_DEVELOPMENT_FLOW
      ,MA.S2PRODUCTTYPE                   AS S2PRODUCTTYPE
      ,MA.S2DERIVATIVETYPE                AS S2DERIVATIVETYPE
      ,MA.S2CFDTEMPLATE                   AS S2CFDTEMPLATE
      ,MA.CFD_CODE                        AS CFD_CODE
      ,OMXMCV.NAME                        AS NAME
      ,OMXMCV.WTDOCUMENTNUMBER            AS WTDOCUMENTNUMBER
      ,OMXMCV.ZBG                         AS ZBG
      ,OMXMCV.ZBU                         AS ZBU
      ,OMXMCV.ZSUBBU                      AS ZSUBBU
      ,OMXMCV.ZPRODUCTLINE                AS ZPRODUCTLINE
      ,OMXMCV.ZPROJECTCODE                AS ZPROJECTCODE
      ,OMXMCV.ZDEVELOPMENTTYPE            AS ZDEVELOPMENTTYPE
      ,OMXMCV.ZPRODUCTTYPE                AS ZPRODUCTTYPE
      ,OMXMCV.ZPROJECTDEVELOPMENTFLOW     AS ZPROJECTDEVELOPMENTFLOW
      ,OMXMCV.ZCFDTEMPLATETYPE            AS ZCFDTEMPLATETYPE
      ,OMXMCV.ZISITADERIVATIVEMODEL       AS ZISITADERIVATIVEMODEL
      ,OMXMCV.ZDERIVATIVETYPE             AS ZDERIVATIVETYPE
FROM ODS.Z_CDOCUMENT_CHECKING_RULE MA  
LEFT JOIN ODS.MV_XXPLM_MODEL_CHECKRULE_V OMXMCV ON MA.S2BU=OMXMCV.ZBG  and MA.S2CURRENTSTAGE= 'C1' AND replace(MA.S2DEVELOPMENTTYPE,' ','')=OMXMCV.ZDEVELOPMENTTYPE AND MA.S2PRODUCTTYPE=OMXMCV.ZPRODUCTTYPE AND MA.PROJECT_DEVELOPMENT_FLOW=OMXMCV.ZPROJECTDEVELOPMENTFLOW AND MA.S2CFDTEMPLATE=OMXMCV.ZCFDTEMPLATETYPE AND  ((OMXMCV.ZISITADERIVATIVEMODEL=OMXMCV.ZISITADERIVATIVEMODEL and MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE) or MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE)
), SDM_UPLOAD_CDOC_COUNT_V12 AS (
      SELECT
       REGEXP_SUBSTR(CFD_CODE, '[^,]+', 1, ROWNUM)      AS CDOC_COMPLETION_RATE
      ,MA.CFD_CODE                        AS CFD_CODE
FROM SDM_UPLOAD_CDOC_COUNT_V11 MA  
CONNECT BY rownum <= LENGTH(CFD_CODE) - LENGTH(REGEXP_REPLACE(CFD_CODE, ',', '')) + 1
), SDM_UPLOAD_CDOC_COUNT_V10 AS (
      SELECT
       distinct MA.CFD_CODE               AS DOC_CODE
      ,C1'                                AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V12 MA  
WHERE MA.CFD_CODE is not null
), SDM_UPLOAD_CDOC_COUNT_V21 AS (
      SELECT
       MA.IDA2A2                          AS IDA2A2
      ,MA.S2BU                            AS S2BU
      ,MA.S2SUBBU                         AS S2SUBBU
      ,replace(MA.S2DEVELOPMENTTYPE,' ','')      AS S2DEVELOPMENTTYPE
      ,MA.S2CURRENTSTAGE                  AS S2CURRENTSTAGE
      ,MA.S2NEXTSTAGE                     AS S2NEXTSTAGE
      ,MA.PROJECT_DEVELOPMENT_FLOW        AS PROJECT_DEVELOPMENT_FLOW
      ,MA.S2PRODUCTTYPE                   AS S2PRODUCTTYPE
      ,MA.S2DERIVATIVETYPE                AS S2DERIVATIVETYPE
      ,MA.S2CFDTEMPLATE                   AS S2CFDTEMPLATE
      ,MA.CFD_CODE                        AS CFD_CODE
      ,OMXMCV.NAME                        AS NAME
      ,OMXMCV.WTDOCUMENTNUMBER            AS WTDOCUMENTNUMBER
      ,OMXMCV.ZBG                         AS ZBG
      ,OMXMCV.ZBU                         AS ZBU
      ,OMXMCV.ZSUBBU                      AS ZSUBBU
      ,OMXMCV.ZPRODUCTLINE                AS ZPRODUCTLINE
      ,OMXMCV.ZPROJECTCODE                AS ZPROJECTCODE
      ,OMXMCV.ZDEVELOPMENTTYPE            AS ZDEVELOPMENTTYPE
      ,OMXMCV.ZPRODUCTTYPE                AS ZPRODUCTTYPE
      ,OMXMCV.ZPROJECTDEVELOPMENTFLOW     AS ZPROJECTDEVELOPMENTFLOW
      ,OMXMCV.ZCFDTEMPLATETYPE            AS ZCFDTEMPLATETYPE
      ,OMXMCV.ZISITADERIVATIVEMODEL       AS ZISITADERIVATIVEMODEL
      ,OMXMCV.ZDERIVATIVETYPE             AS ZDERIVATIVETYPE
FROM ODS.Z_CDOCUMENT_CHECKING_RULE MA  
LEFT JOIN ODS.MV_XXPLM_MODEL_CHECKRULE_V OMXMCV ON MA.S2BU=OMXMCV.ZBG  and MA.S2CURRENTSTAGE= 'C23' AND replace(MA.S2DEVELOPMENTTYPE,' ','')=OMXMCV.ZDEVELOPMENTTYPE AND MA.S2PRODUCTTYPE=OMXMCV.ZPRODUCTTYPE AND MA.PROJECT_DEVELOPMENT_FLOW=OMXMCV.ZPROJECTDEVELOPMENTFLOW AND MA.S2CFDTEMPLATE=OMXMCV.ZCFDTEMPLATETYPE AND  ((OMXMCV.ZISITADERIVATIVEMODEL=OMXMCV.ZISITADERIVATIVEMODEL and MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE) or MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE)
), SDM_UPLOAD_CDOC_COUNT_V22 AS (
      SELECT
       REGEXP_SUBSTR(CFD_CODE, '[^,]+', 1, ROWNUM)      AS CDOC_COMPLETION_RATE
      ,MA.CFD_CODE                        AS CFD_CODE
FROM SDM_UPLOAD_CDOC_COUNT_V21 MA  
CONNECT BY rownum <= LENGTH(CFD_CODE) - LENGTH(REGEXP_REPLACE(CFD_CODE, ',', '')) + 1
), SDM_UPLOAD_CDOC_COUNT_V20 AS (
      SELECT
       distinct MA.CFD_CODE               AS DOC_CODE
      ,C23'                               AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V22 MA  
WHERE MA.CFD_CODE is not null
), SDM_UPLOAD_CDOC_COUNT_V31 AS (
      SELECT
       MA.IDA2A2                          AS IDA2A2
      ,MA.S2BU                            AS S2BU
      ,MA.S2SUBBU                         AS S2SUBBU
      ,replace(MA.S2DEVELOPMENTTYPE,' ','')      AS S2DEVELOPMENTTYPE
      ,MA.S2CURRENTSTAGE                  AS S2CURRENTSTAGE
      ,MA.S2NEXTSTAGE                     AS S2NEXTSTAGE
      ,MA.PROJECT_DEVELOPMENT_FLOW        AS PROJECT_DEVELOPMENT_FLOW
      ,MA.S2PRODUCTTYPE                   AS S2PRODUCTTYPE
      ,MA.S2DERIVATIVETYPE                AS S2DERIVATIVETYPE
      ,MA.S2CFDTEMPLATE                   AS S2CFDTEMPLATE
      ,MA.CFD_CODE                        AS CFD_CODE
      ,OMXMCV.NAME                        AS NAME
      ,OMXMCV.WTDOCUMENTNUMBER            AS WTDOCUMENTNUMBER
      ,OMXMCV.ZBG                         AS ZBG
      ,OMXMCV.ZBU                         AS ZBU
      ,OMXMCV.ZSUBBU                      AS ZSUBBU
      ,OMXMCV.ZPRODUCTLINE                AS ZPRODUCTLINE
      ,OMXMCV.ZPROJECTCODE                AS ZPROJECTCODE
      ,OMXMCV.ZDEVELOPMENTTYPE            AS ZDEVELOPMENTTYPE
      ,OMXMCV.ZPRODUCTTYPE                AS ZPRODUCTTYPE
      ,OMXMCV.ZPROJECTDEVELOPMENTFLOW     AS ZPROJECTDEVELOPMENTFLOW
      ,OMXMCV.ZCFDTEMPLATETYPE            AS ZCFDTEMPLATETYPE
      ,OMXMCV.ZISITADERIVATIVEMODEL       AS ZISITADERIVATIVEMODEL
      ,OMXMCV.ZDERIVATIVETYPE             AS ZDERIVATIVETYPE
FROM ODS.Z_CDOCUMENT_CHECKING_RULE MA  
LEFT JOIN ODS.MV_XXPLM_MODEL_CHECKRULE_V OMXMCV ON MA.S2BU=OMXMCV.ZBG  and MA.S2CURRENTSTAGE= 'C4' AND replace(MA.S2DEVELOPMENTTYPE,' ','')=OMXMCV.ZDEVELOPMENTTYPE AND MA.S2PRODUCTTYPE=OMXMCV.ZPRODUCTTYPE AND MA.PROJECT_DEVELOPMENT_FLOW=OMXMCV.ZPROJECTDEVELOPMENTFLOW AND MA.S2CFDTEMPLATE=OMXMCV.ZCFDTEMPLATETYPE AND  ((OMXMCV.ZISITADERIVATIVEMODEL=OMXMCV.ZISITADERIVATIVEMODEL and MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE) or MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE)
), SDM_UPLOAD_CDOC_COUNT_V32 AS (
      SELECT
       REGEXP_SUBSTR(CFD_CODE, '[^,]+', 1, ROWNUM)      AS CDOC_COMPLETION_RATE
      ,MA.CFD_CODE                        AS CFD_CODE
FROM SDM_UPLOAD_CDOC_COUNT_V31 MA  
CONNECT BY rownum <= LENGTH(CFD_CODE) - LENGTH(REGEXP_REPLACE(CFD_CODE, ',', '')) + 1
), SDM_UPLOAD_CDOC_COUNT_V30 AS (
      SELECT
       distinct MA.CFD_CODE               AS DOC_CODE
      ,C4'                                AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V32 MA  
WHERE MA.CFD_CODE is not null
), SDM_UPLOAD_CDOC_COUNT_V41 AS (
      SELECT
       MA.IDA2A2                          AS IDA2A2
      ,MA.S2BU                            AS S2BU
      ,MA.S2SUBBU                         AS S2SUBBU
      ,replace(MA.S2DEVELOPMENTTYPE,' ','')      AS S2DEVELOPMENTTYPE
      ,MA.S2CURRENTSTAGE                  AS S2CURRENTSTAGE
      ,MA.S2NEXTSTAGE                     AS S2NEXTSTAGE
      ,MA.PROJECT_DEVELOPMENT_FLOW        AS PROJECT_DEVELOPMENT_FLOW
      ,MA.S2PRODUCTTYPE                   AS S2PRODUCTTYPE
      ,MA.S2DERIVATIVETYPE                AS S2DERIVATIVETYPE
      ,MA.S2CFDTEMPLATE                   AS S2CFDTEMPLATE
      ,MA.CFD_CODE                        AS CFD_CODE
      ,OMXMCV.NAME                        AS NAME
      ,OMXMCV.WTDOCUMENTNUMBER            AS WTDOCUMENTNUMBER
      ,OMXMCV.ZBG                         AS ZBG
      ,OMXMCV.ZBU                         AS ZBU
      ,OMXMCV.ZSUBBU                      AS ZSUBBU
      ,OMXMCV.ZPRODUCTLINE                AS ZPRODUCTLINE
      ,OMXMCV.ZPROJECTCODE                AS ZPROJECTCODE
      ,OMXMCV.ZDEVELOPMENTTYPE            AS ZDEVELOPMENTTYPE
      ,OMXMCV.ZPRODUCTTYPE                AS ZPRODUCTTYPE
      ,OMXMCV.ZPROJECTDEVELOPMENTFLOW     AS ZPROJECTDEVELOPMENTFLOW
      ,OMXMCV.ZCFDTEMPLATETYPE            AS ZCFDTEMPLATETYPE
      ,OMXMCV.ZISITADERIVATIVEMODEL       AS ZISITADERIVATIVEMODEL
      ,OMXMCV.ZDERIVATIVETYPE             AS ZDERIVATIVETYPE
FROM ODS.Z_CDOCUMENT_CHECKING_RULE MA  
LEFT JOIN ODS.MV_XXPLM_MODEL_CHECKRULE_V OMXMCV ON MA.S2BU=OMXMCV.ZBG  and MA.S2CURRENTSTAGE= 'C5' AND replace(MA.S2DEVELOPMENTTYPE,' ','')=OMXMCV.ZDEVELOPMENTTYPE AND MA.S2PRODUCTTYPE=OMXMCV.ZPRODUCTTYPE AND MA.PROJECT_DEVELOPMENT_FLOW=OMXMCV.ZPROJECTDEVELOPMENTFLOW AND MA.S2CFDTEMPLATE=OMXMCV.ZCFDTEMPLATETYPE AND  ((OMXMCV.ZISITADERIVATIVEMODEL=OMXMCV.ZISITADERIVATIVEMODEL and MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE) or MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE)
), SDM_UPLOAD_CDOC_COUNT_V42 AS (
      SELECT
       REGEXP_SUBSTR(CFD_CODE, '[^,]+', 1, ROWNUM)      AS CDOC_COMPLETION_RATE
      ,MA.CFD_CODE                        AS CFD_CODE
FROM SDM_UPLOAD_CDOC_COUNT_V41 MA  
CONNECT BY rownum <= LENGTH(CFD_CODE) - LENGTH(REGEXP_REPLACE(CFD_CODE, ',', '')) + 1
), SDM_UPLOAD_CDOC_COUNT_V40 AS (
      SELECT
       distinct MA.CFD_CODE               AS DOC_CODE
      ,C5'                                AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V42 MA  
WHERE MA.CFD_CODE is not null
), SDM_UPLOAD_CDOC_COUNT_V51 AS (
      SELECT
       MA.IDA2A2                          AS IDA2A2
      ,MA.S2BU                            AS S2BU
      ,MA.S2SUBBU                         AS S2SUBBU
      ,replace(MA.S2DEVELOPMENTTYPE,' ','')      AS S2DEVELOPMENTTYPE
      ,MA.S2CURRENTSTAGE                  AS S2CURRENTSTAGE
      ,MA.S2NEXTSTAGE                     AS S2NEXTSTAGE
      ,MA.PROJECT_DEVELOPMENT_FLOW        AS PROJECT_DEVELOPMENT_FLOW
      ,MA.S2PRODUCTTYPE                   AS S2PRODUCTTYPE
      ,MA.S2DERIVATIVETYPE                AS S2DERIVATIVETYPE
      ,MA.S2CFDTEMPLATE                   AS S2CFDTEMPLATE
      ,MA.CFD_CODE                        AS CFD_CODE
      ,OMXMCV.NAME                        AS NAME
      ,OMXMCV.WTDOCUMENTNUMBER            AS WTDOCUMENTNUMBER
      ,OMXMCV.ZBG                         AS ZBG
      ,OMXMCV.ZBU                         AS ZBU
      ,OMXMCV.ZSUBBU                      AS ZSUBBU
      ,OMXMCV.ZPRODUCTLINE                AS ZPRODUCTLINE
      ,OMXMCV.ZPROJECTCODE                AS ZPROJECTCODE
      ,OMXMCV.ZDEVELOPMENTTYPE            AS ZDEVELOPMENTTYPE
      ,OMXMCV.ZPRODUCTTYPE                AS ZPRODUCTTYPE
      ,OMXMCV.ZPROJECTDEVELOPMENTFLOW     AS ZPROJECTDEVELOPMENTFLOW
      ,OMXMCV.ZCFDTEMPLATETYPE            AS ZCFDTEMPLATETYPE
      ,OMXMCV.ZISITADERIVATIVEMODEL       AS ZISITADERIVATIVEMODEL
      ,OMXMCV.ZDERIVATIVETYPE             AS ZDERIVATIVETYPE
FROM ODS.Z_CDOCUMENT_CHECKING_RULE MA  
LEFT JOIN ODS.MV_XXPLM_MODEL_CHECKRULE_V OMXMCV ON MA.S2BU=OMXMCV.ZBG  and MA.S2CURRENTSTAGE= 'C6' AND replace(MA.S2DEVELOPMENTTYPE,' ','')=OMXMCV.ZDEVELOPMENTTYPE AND MA.S2PRODUCTTYPE=OMXMCV.ZPRODUCTTYPE AND MA.PROJECT_DEVELOPMENT_FLOW=OMXMCV.ZPROJECTDEVELOPMENTFLOW AND MA.S2CFDTEMPLATE=OMXMCV.ZCFDTEMPLATETYPE AND  ((OMXMCV.ZISITADERIVATIVEMODEL=OMXMCV.ZISITADERIVATIVEMODEL and MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE) or MA.S2DERIVATIVETYPE=OMXMCV.ZDERIVATIVETYPE)
), SDM_UPLOAD_CDOC_COUNT_V52 AS (
      SELECT
       REGEXP_SUBSTR(CFD_CODE, '[^,]+', 1, ROWNUM)      AS CDOC_COMPLETION_RATE
      ,MA.CFD_CODE                        AS CFD_CODE
FROM SDM_UPLOAD_CDOC_COUNT_V51 MA  
CONNECT BY rownum <= LENGTH(CFD_CODE) - LENGTH(REGEXP_REPLACE(CFD_CODE, ',', '')) + 1
), SDM_UPLOAD_CDOC_COUNT_V50 AS (
      SELECT
       distinct MA.CFD_CODE               AS DOC_CODE
      ,C6'                                AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V52 MA  
WHERE MA.CFD_CODE is not null
), SDM_UPLOAD_CDOC_COUNT_V90 AS (
      SELECT
       REGEXP_SUBSTR (DOC_CODE, '[^,]+', 1,ROWNUM)      AS DOC_CODE
      ,MA.STAGE                           AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V10 MA  
UNION ALL 
      SELECT
       REGEXP_SUBSTR (DOC_CODE, '[^,]+', 1,ROWNUM)      AS DOC_CODE
      ,MA.STAGE                           AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V20 MA  
UNION ALL 
      SELECT
       REGEXP_SUBSTR (DOC_CODE, '[^,]+', 1,ROWNUM)      AS DOC_CODE
      ,MA.STAGE                           AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V30 MA  
UNION ALL 
      SELECT
       REGEXP_SUBSTR (DOC_CODE, '[^,]+', 1,ROWNUM)      AS DOC_CODE
      ,MA.STAGE                           AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V40 MA  
UNION ALL 
      SELECT
       REGEXP_SUBSTR (DOC_CODE, '[^,]+', 1,ROWNUM)      AS DOC_CODE
      ,MA.STAGE                           AS STAGE
FROM SDM_UPLOAD_CDOC_COUNT_V50 MA  
), SDM_UPLOAD_CDOC_COUNT_V99 AS (
      SELECT
       N/A'                               AS PROJECT_CODE
      ,N/A'                               AS BUSINESS_GROUP
      ,MA.MODEL_NO                        AS MODEL
      ,N/A'                               AS MANUFACTURING_PLANT
      ,MA.doccode                         AS DOC_CODE
      ,SUCCV.STAGE                        AS STAGE
      ,count(1)                           AS UPLOAD_CDOC_COUNT
FROM ODS.MV_XXPLM_CFDMETADATA MA  
JOIN SDM_UPLOAD_CDOC_COUNT_V90 SUCCV ON MA.doccode=SUCCV.DOC_CODE
GROUP BY N/A',N/A',MA.MODEL_NO,N/A',MA.doccode,SUCCV.STAGE
)      SELECT
       MA.PROJECT_CODE                    AS PROJECT_CODE
      ,MA.BUSINESS_GROUP                  AS BUSINESS_GROUP
      ,MA.MODEL                           AS MODEL
      ,MA.MANUFACTURING_PLANT             AS MANUFACTURING_PLANT
      ,MA.DOC_CODE                        AS DOC_CODE
      ,MA.STAGE                           AS STAGE
      ,MA.UPLOAD_CDOC_COUNT               AS UPLOAD_CDOC_COUNT
FROM SDM_UPLOAD_CDOC_COUNT_V99 MA  
;


ALTER TABLE SDM.SDM_UPLOAD_CDOC_COUNT DISABLE CONSTRAINT SDM_UPLOAD_CDOC_COUNT_X;
TRUNCATE TABLE SDM.SDM_UPLOAD_CDOC_COUNT;

INSERT /*+ append */ INTO SDM.SDM_UPLOAD_CDOC_COUNT (
      PROJECT_CODE                            
      ,BUSINESS_GROUP                          
      ,MODEL                                   
      ,MANUFACTURING_PLANT                     
      ,DOC_CODE                                
      ,STAGE                                   
      ,UPLOAD_CDOC_COUNT                       
      ,DATA_DATE                               
      ,TBL_UPD_TIME                            
      ,TBL_UPD_SRC                             
) 
      SELECT
      MA.PROJECT_CODE                         
      ,MA.BUSINESS_GROUP                       
      ,MA.MODEL                                
      ,MA.MANUFACTURING_PLANT                  
      ,MA.DOC_CODE                             
      ,MA.STAGE                                
      ,MA.UPLOAD_CDOC_COUNT                    
      ,'20201108'                            
      ,CURRENT_DATE                         
      ,'SDM_UPLOAD_CDOC_COUNT_V99'                          
FROM SDM.SDM_UPLOAD_CDOC_COUNT_TP1 MA ; 



ALTER TABLE SDM.SDM_UPLOAD_CDOC_COUNT ENABLE CONSTRAINT SDM_UPLOAD_CDOC_COUNT_X EXCEPTIONS INTO SDM.SDM_UPLOAD_CDOC_COUNT_TPX;

-- Update statistics
CALL DBMS_STATS.GATHER_TABLE_STATS('SDM','SDM_UPLOAD_CDOC_COUNT');


